import type { GrammarGroup } from "../types";

export const adjectivesAdverbs: GrammarGroup = {
  id: "adjectives-adverbs",
  description: "Adjectives describe nouns; adverbs describe verbs, adjectives and other adverbs. This group covers how to form and place them correctly.",
  azDescription: "Sifət (adjective) ismi, yəni əşyanı və ya insanı təsvir edir (a fast car, a kind teacher). Zərf (adverb) isə feili, sifəti və ya başqa bir zərfi təsvir edir və çox vaxt işin NECƏ görüldüyünü bildirir (he runs fast). Bu bölmədə sifət və zərflərin necə düzəldildiyini, cümlədə hansı yerdə durduğunu və hansı sözlərlə birlikdə işləndiyini öyrənəcəksən.",
  rules: [
    {
      title: "Adjective vs adverb (forming adverbs with -ly)",
      level: "B1",
      explanation: "An adjective describes a noun. An adverb describes a verb, and is often made by adding -ly to the adjective.",
      azNote: "Sifət (adjective) ismi təsvir edir, yəni hansı növ olduğunu göstərir (a quick runner). Zərf (adverb) isə feili təsvir edir və işin NECƏ baş verdiyini bildirir (she runs quickly). Bir çox zərfi sifətin sonuna -ly əlavə etməklə düzəldirik: quick -> quickly, careful -> carefully.",
      form: "adjective + -ly = adverb",
      examples: [
        { en: "She is a quick runner.", note: "'quick' describes the noun 'runner'" },
        { en: "She runs quickly.", note: "'quickly' describes the verb 'runs'" },
        { en: "He gave a careful answer and answered carefully.", note: "adjective then adverb" },
      ],
      pitfall: "Feildən sonra sifət yox, zərf işlət: 'He drives careful' yox, 'He drives carefully'.",
    },
    {
      title: "-ed vs -ing adjectives (bored vs boring)",
      level: "B1",
      explanation: "Use -ed adjectives for how a person feels. Use -ing adjectives for the thing that causes the feeling.",
      azNote: "-ed ilə bitən sifət insanın özünü NECƏ hiss etdiyini bildirir (I am bored = mən darıxmışam). -ing ilə bitən sifət isə həmin hissi YARADAN şeyi və ya səbəbi bildirir (the lesson is boring = dərs darıxdırıcıdır). Yəni insan üçün -ed, o hissin səbəbi üçün -ing işlədirik.",
      form: "person + -ed adjective; thing + -ing adjective",
      examples: [
        { en: "I am bored in this lesson.", note: "how the person feels" },
        { en: "This lesson is boring.", note: "the lesson causes the feeling" },
        { en: "She is interested because the book is interesting.", note: "both forms together" },
      ],
      pitfall: "'I am boring' demə (özünü darıxdırıcı adlandırırsan); düzgünü 'I am bored'.",
    },
    {
      title: "Adverbs of frequency (position)",
      level: "B1",
      explanation: "Adverbs of frequency like always, usually, often, sometimes, never go before the main verb but after the verb 'be'.",
      azNote: "Tezlik zərfləri (işin nə qədər tez-tez baş verdiyini bildirən sözlər) - always, usually, often, sometimes, never - adi əsas feildən ÖNCƏ gəlir (I always drink coffee). Ancaq 'be' (am/is/are) feili ilə işlənəndə bu zərflər feildən SONRA durur (she is never late). Yəni qaydanı belə yadda saxla: əsas feildən əvvəl, 'be' feilindən sonra.",
      form: "subject + adverb + main verb; subject + be + adverb",
      examples: [
        { en: "I always drink coffee in the morning.", note: "before the main verb 'drink'" },
        { en: "She is never late for work.", note: "after the verb 'be'" },
        { en: "We usually go out on Fridays.", note: "before the main verb 'go'" },
      ],
      pitfall: "'be' ilə yerini dəyişmə: 'He is often tired' düzdür, 'He often is tired' yox.",
    },
    {
      title: "Irregular adverbs (good/well, fast, hard, hardly)",
      level: "B2",
      explanation: "Some adverbs are irregular. 'good' becomes 'well'. 'fast' and 'hard' stay the same. 'hardly' is a different word meaning 'almost not'.",
      azNote: "Bəzi zərflər ümumi -ly qaydasına tabe olmur. 'good' sifətinin zərfi 'well' olur (she speaks English well). 'fast' və 'hard' həm sifət, həm də zərf kimi eyni qalır (he works hard). Diqqət: 'hardly' tamam ayrı bir sözdür və 'demək olar ki, heç' mənasını verir (I could hardly hear you = səni demək olar ki, eşidə bilmədim).",
      form: "good (adj) > well (adv); fast/hard (adj = adv)",
      examples: [
        { en: "She speaks English well.", note: "adverb of 'good' is 'well'" },
        { en: "He works hard every day.", note: "'hard' is both adjective and adverb" },
        { en: "I could hardly hear you.", note: "'hardly' means 'almost not'" },
      ],
      pitfall: "'hard' və 'hardly' eyni deyil: 'work hard' = çox çalışmaq, 'hardly work' = demək olar ki, işləməmək.",
    },
    {
      title: "Order of adjectives",
      level: "B2",
      explanation: "When several adjectives describe one noun, they follow an order: opinion, size, age, shape, colour, origin, material.",
      azNote: "Bir ismi eyni anda bir neçə sifət təsvir edəndə, onlar müəyyən sıra ilə düzülməlidir. Sıra belədir: rəy (lovely), ölçü (small), yaş (old), forma (round), rəng (red), mənşə/haradan olduğu (Italian), material (leather). Məsələn: a lovely small old round table. Bu sıranı pozmaq cümləni qeyri-təbii edir.",
      form: "opinion - size - age - shape - colour - origin - material + noun",
      examples: [
        { en: "A lovely small old round table.", note: "opinion, size, age, shape" },
        { en: "A beautiful red Italian car.", note: "opinion, colour, origin" },
        { en: "An expensive new leather bag.", note: "opinion, age, material" },
      ],
      pitfall: "Rəngi rəy və ölçüdən əvvəl qoyma: 'a red big ball' yox, 'a big red ball'.",
    },
    {
      title: "Gradable vs non-gradable adjectives",
      level: "B2",
      explanation: "Gradable adjectives (tired, big) take 'very'. Non-gradable, extreme adjectives (exhausted, huge) take 'absolutely', not 'very'.",
      azNote: "Adi (dərəcələnə bilən) sifətlərin azı və çoxu olur, ona görə onlarla 'very' işlədirik (very tired, very big). Güclü/ekstremal sifətlərin isə özündə artıq 'çox' mənası var (exhausted = lap əldən düşmüş, huge = nəhəng), buna görə onlarla 'very' deyil, 'absolutely' işlədirik (absolutely exhausted). Sadə dillə: adi sifət üçün 'very', güclü sifət üçün 'absolutely'.",
      form: "very + gradable; absolutely + non-gradable",
      examples: [
        { en: "I am very tired after work.", note: "'very' with a gradable adjective" },
        { en: "I am absolutely exhausted.", note: "'absolutely' with an extreme adjective" },
        { en: "The film was absolutely amazing.", note: "extreme adjective 'amazing'" },
      ],
      pitfall: "'very exhausted' təbii deyil; ekstremal sifətlərlə 'absolutely' işlət.",
    },
    {
      title: "so vs such",
      level: "B2",
      explanation: "Use 'so' before an adjective or adverb alone. Use 'such' before (a/an) + adjective + noun.",
      azNote: "Hər ikisi 'o qədər / belə' mənasını gücləndirmək üçün işlənir, fərq isə yanındakı sözdədir. 'so' təkcə sifət və ya zərfdən əvvəl gəlir, yəni isim olmayanda (the test was so difficult; she drives so carefully). 'such' isə isim olanda işlənir: (a/an) + sifət + isim (it was such a difficult test). Qısaca: isim varsa 'such', yoxdursa 'so'.",
      form: "so + adjective/adverb; such + (a) + adjective + noun",
      examples: [
        { en: "The test was so difficult.", note: "'so' + adjective alone" },
        { en: "It was such a difficult test.", note: "'such' + a + adjective + noun" },
        { en: "She drives so carefully.", note: "'so' + adverb" },
      ],
      pitfall: "İsim varsa 'so' yox 'such' işlət: 'so a nice day' yox, 'such a nice day'.",
    },
  ],
  practice: [
    {
      type: "multiple-choice",
      prompt: "He plays the guitar very ___.",
      options: ["good", "well", "goodly"],
      answer: 1,
      explanation: "The adverb of 'good' is the irregular form 'well', describing the verb 'plays'.",
    },
    {
      type: "gap-fill",
      prompt: "The journey was long, so I am very ___ now. (-ed/-ing: tire)",
      answer: "tired",
      explanation: "The person feels the effect, so use the -ed adjective 'tired'.",
    },
    {
      type: "multiple-choice",
      prompt: "This documentary is really ___; I learned a lot.",
      options: ["interested", "interesting", "interest"],
      answer: 1,
      explanation: "The documentary causes the feeling, so use the -ing adjective 'interesting'.",
    },
    {
      type: "gap-fill",
      prompt: "She is ___ late for meetings; she always arrives on time. (frequency adverb after 'be')",
      answer: "never",
      explanation: "Adverbs of frequency go after the verb 'be': 'She is never late'.",
    },
    {
      type: "multiple-choice",
      prompt: "I bought ___.",
      options: ["a leather black old bag", "an old black leather bag", "a black old leather bag"],
      answer: 1,
      explanation: "Order is age (old), colour (black), material (leather): 'an old black leather bag'.",
    },
    {
      type: "gap-fill",
      prompt: "After running the marathon, he was absolutely ___. (extreme adjective for very tired)",
      answer: "exhausted",
      explanation: "'absolutely' goes with the non-gradable, extreme adjective 'exhausted'.",
    },
    {
      type: "multiple-choice",
      prompt: "It was ___ a beautiful day that we went to the beach.",
      options: ["so", "such", "very"],
      answer: 1,
      explanation: "Before 'a + adjective + noun' we use 'such', not 'so'.",
    },
    {
      type: "gap-fill",
      prompt: "Please listen ___ to the instructions. (adverb of 'careful')",
      answer: "carefully",
      explanation: "We need an adverb to describe the verb 'listen', formed by adding -ly: 'carefully'.",
    },
  ],
};
