import type { GrammarGroup } from "../types";

export const adjectivesAdverbs: GrammarGroup = {
  id: "adjectives-adverbs",
  description: "Adjectives describe nouns; adverbs describe verbs, adjectives and other adverbs. This group covers how to form and place them correctly.",
  azDescription: "Sifetler isimleri tesvir edir; zerfler ise feilleri, sifetleri ve diger zerfleri tesvir edir. Bu bolme onlarin duzgun yaranmasi ve yerlesmesini ehate edir.",
  rules: [
    {
      title: "Adjective vs adverb (forming adverbs with -ly)",
      level: "B1",
      explanation: "An adjective describes a noun. An adverb describes a verb, and is often made by adding -ly to the adjective.",
      azNote: "Sifet ismi, zerf feili tesvir edir. Cox vaxt sifete -ly elave edib zerf duzeldirik (quick > quickly).",
      form: "adjective + -ly = adverb",
      examples: [
        { en: "She is a quick runner.", note: "'quick' describes the noun 'runner'" },
        { en: "She runs quickly.", note: "'quickly' describes the verb 'runs'" },
        { en: "He gave a careful answer and answered carefully.", note: "adjective then adverb" },
      ],
      pitfall: "Feilden sonra sifet yox, zerf isledin: 'He drives careful' yox, 'He drives carefully'.",
    },
    {
      title: "Irregular adverbs (good/well, fast, hard, hardly)",
      level: "B2",
      explanation: "Some adverbs are irregular. 'good' becomes 'well'. 'fast' and 'hard' stay the same. 'hardly' is a different word meaning 'almost not'.",
      azNote: "Bezi zerfler qaydasizdir: good > well; fast ve hard deyismir. 'hardly' ise 'demek olar ki yox' demekdir.",
      form: "good (adj) > well (adv); fast/hard (adj = adv)",
      examples: [
        { en: "She speaks English well.", note: "adverb of 'good' is 'well'" },
        { en: "He works hard every day.", note: "'hard' is both adjective and adverb" },
        { en: "I could hardly hear you.", note: "'hardly' means 'almost not'" },
      ],
      pitfall: "'hard' ve 'hardly' eyni deyil: 'work hard' = cox calismaq, 'hardly work' = demek olar ki islememek.",
    },
    {
      title: "-ed vs -ing adjectives (bored vs boring)",
      level: "B1",
      explanation: "Use -ed adjectives for how a person feels. Use -ing adjectives for the thing that causes the feeling.",
      azNote: "-ed sifet insanin hissini bildirir (bored = darixmis). -ing sifet o hissi yaradan seyi bildirir (boring = darixdirici).",
      form: "person + -ed adjective; thing + -ing adjective",
      examples: [
        { en: "I am bored in this lesson.", note: "how the person feels" },
        { en: "This lesson is boring.", note: "the lesson causes the feeling" },
        { en: "She is interested because the book is interesting.", note: "both forms together" },
      ],
      pitfall: "'I am boring' demeyin (ozunuzu darixdirici adlandirirsiniz); duzgunu 'I am bored'.",
    },
    {
      title: "Adverbs of frequency (position)",
      level: "B1",
      explanation: "Adverbs of frequency like always, usually, often, sometimes, never go before the main verb but after the verb 'be'.",
      azNote: "always, usually, often, sometimes, never esas feilden ONCE, lakin 'be' feilinden SONRA gelir.",
      form: "subject + adverb + main verb; subject + be + adverb",
      examples: [
        { en: "I always drink coffee in the morning.", note: "before the main verb 'drink'" },
        { en: "She is never late for work.", note: "after the verb 'be'" },
        { en: "We usually go out on Fridays.", note: "before the main verb 'go'" },
      ],
      pitfall: "'be' ile yerini deyisme: 'He is often tired' duzdur, 'He often is tired' deyil.",
    },
    {
      title: "Order of adjectives",
      level: "B2",
      explanation: "When several adjectives describe one noun, they follow an order: opinion, size, age, shape, colour, origin, material.",
      azNote: "Bir isimden once bir nece sifet olanda siralama: rey, olcu, yas, forma, reng, mensubiyyet, material.",
      form: "opinion - size - age - shape - colour - origin - material + noun",
      examples: [
        { en: "A lovely small old round table.", note: "opinion, size, age, shape" },
        { en: "A beautiful red Italian car.", note: "opinion, colour, origin" },
        { en: "An expensive new leather bag.", note: "opinion, age, material" },
      ],
      pitfall: "Rengi rey ve olcuden once qoymayin: 'a red big ball' yox, 'a big red ball'.",
    },
    {
      title: "Gradable vs non-gradable adjectives",
      level: "B2",
      explanation: "Gradable adjectives (tired, big) take 'very'. Non-gradable, extreme adjectives (exhausted, huge) take 'absolutely', not 'very'.",
      azNote: "Adi sifetler (tired) 'very' qebul edir. Guclu/ekstremal sifetler (exhausted) 'absolutely' isteyir, 'very' yox.",
      form: "very + gradable; absolutely + non-gradable",
      examples: [
        { en: "I am very tired after work.", note: "'very' with a gradable adjective" },
        { en: "I am absolutely exhausted.", note: "'absolutely' with an extreme adjective" },
        { en: "The film was absolutely amazing.", note: "extreme adjective 'amazing'" },
      ],
      pitfall: "'very exhausted' tebii deyil; ekstremal sifetlerle 'absolutely' isledin.",
    },
    {
      title: "so vs such",
      level: "B2",
      explanation: "Use 'so' before an adjective or adverb alone. Use 'such' before (a/an) + adjective + noun.",
      azNote: "'so' tek sifet/zerfden once gelir. 'such' ise (a/an) + sifet + isimden once gelir.",
      form: "so + adjective/adverb; such + (a) + adjective + noun",
      examples: [
        { en: "The test was so difficult.", note: "'so' + adjective alone" },
        { en: "It was such a difficult test.", note: "'such' + a + adjective + noun" },
        { en: "She drives so carefully.", note: "'so' + adverb" },
      ],
      pitfall: "Isim varsa 'so' yox 'such' isledin: 'so a nice day' yox, 'such a nice day'.",
    },
  ],
  practice: [
    {
      type: "multiple-choice",
      prompt: "He plays the guitar very ___.",
      options: ["good", "well", "goodly"],
      answer: 1,
      explanation: "The adverb of 'good' is the irregular form 'well', describing the verb 'plays'.",
    },
    {
      type: "gap-fill",
      prompt: "The journey was long, so I am very ___ now. (-ed/-ing: tire)",
      answer: "tired",
      explanation: "The person feels the effect, so use the -ed adjective 'tired'.",
    },
    {
      type: "multiple-choice",
      prompt: "This documentary is really ___; I learned a lot.",
      options: ["interested", "interesting", "interest"],
      answer: 1,
      explanation: "The documentary causes the feeling, so use the -ing adjective 'interesting'.",
    },
    {
      type: "gap-fill",
      prompt: "She is ___ late for meetings; she always arrives on time. (frequency adverb after 'be')",
      answer: "never",
      explanation: "Adverbs of frequency go after the verb 'be': 'She is never late'.",
    },
    {
      type: "multiple-choice",
      prompt: "I bought ___.",
      options: ["a leather black old bag", "an old black leather bag", "a black old leather bag"],
      answer: 1,
      explanation: "Order is age (old), colour (black), material (leather): 'an old black leather bag'.",
    },
    {
      type: "gap-fill",
      prompt: "After running the marathon, he was absolutely ___. (extreme adjective for very tired)",
      answer: "exhausted",
      explanation: "'absolutely' goes with the non-gradable, extreme adjective 'exhausted'.",
    },
    {
      type: "multiple-choice",
      prompt: "It was ___ a beautiful day that we went to the beach.",
      options: ["so", "such", "very"],
      answer: 1,
      explanation: "Before 'a + adjective + noun' we use 'such', not 'so'.",
    },
    {
      type: "gap-fill",
      prompt: "Please listen ___ to the instructions. (adverb of 'careful')",
      answer: "carefully",
      explanation: "We need an adverb to describe the verb 'listen', formed by adding -ly: 'carefully'.",
    },
  ],
};
