import type { GrammarGroup } from "../types";

export const comparatives: GrammarGroup = {
  id: "comparatives",
  description: "Comparatives and superlatives let us compare two or more things by degree.",
  azDescription: "Müqayisə dərəcələri (comparatives və superlatives) bir şeyi başqası ilə bir keyfiyyət baxımından tutuşdurmağa kömək edir. Comparative iki şeyi qarşılaşdıranda işlədilir (məsələn, biri o birindən daha böyük və ya daha ucuzdursa). Superlative isə bir şeyi bütöv bir qrupun içində ən üstün və ya ən aşağı kimi göstərir (məsələn, qrupda ən hündür). Bu bölmədə həmin formaları və onlardan necə istifadə olunduğunu öyrənəcəksən.",
  rules: [
    {
      title: "Comparative adjectives: short vs long",
      level: "B1",
      explanation: "Short adjectives take '-er'. Long adjectives (two or more syllables) use 'more'. We add 'than' to name the second thing.",
      azNote: "İki şeyi tutuşdurarkən comparative işlədirik. Qısa (adətən bir hecalı) sifətlərə '-er' sonluğu əlavə olunur: cheap -> cheaper. Uzun (iki və daha çox hecalı) sifətlərin qarşısına isə 'more' qoyulur: interesting -> more interesting. Müqayisə olunan ikinci tərəfdən əvvəl 'than' (-dən/-dan) gəlir. Qeyd: hot kimi bəzi sifətlərdə son samit qoşalaşır (hot -> hotter).",
      form: "short adjective + -er + than  ·  more + long adjective + than",
      examples: [
        { en: "My bag is cheaper than yours.", note: "short adjective + -er" },
        { en: "This book is more interesting than the film.", note: "long adjective + more" },
        { en: "Today is hotter than yesterday.", note: "double the final consonant: hot -> hotter" },
      ],
      pitfall: "'more cheaper' deyilmir. Ya '-er', ya da 'more' seç, ikisi birlikdə olmaz.",
    },
    {
      title: "Superlative adjectives: the -est / the most",
      level: "B1",
      explanation: "Superlatives compare one thing with a whole group. Short adjectives take 'the ...-est'; long adjectives take 'the most ...'.",
      azNote: "Superlative bir şeyi bütöv bir qrupun içində ən üstün kimi göstərir (məsələn, sinifdə ən hündür). Qısa sifətə 'the ...-est' əlavə edirik: tall -> the tallest. Uzun sifətin qarşısına isə 'the most' qoyuruq: expensive -> the most expensive. Superlativdən əvvəl 'the' artikli demək olar ki, həmişə vacibdir. Diqqət: 'y' ilə bitən sifətlərdə 'y' -> 'i' olur (easy -> easiest).",
      form: "the + short adjective + -est  ·  the most + long adjective",
      examples: [
        { en: "She is the tallest student in the class.", note: "short adjective + -est" },
        { en: "It was the most expensive meal of the trip.", note: "long adjective + most" },
        { en: "This is the easiest exercise in the book.", note: "y changes to i: easy -> easiest" },
      ],
      pitfall: "Superlativdən əvvəl 'the' düşür: 'most expensive' YOX -> 'the most expensive'.",
    },
    {
      title: "as ... as (equality) and not as ... as",
      level: "B1",
      explanation: "Use 'as + adjective + as' to say two things are equal. 'not as ... as' shows they are not equal.",
      azNote: "İki şeyin hansısa keyfiyyətdə eyni (bərabər) olduğunu bildirmək üçün 'as + sifət + as' quruluşunu işlədirik: as tall as (qədər hündür). Bərabər olmadıqlarını demək üçün isə 'not as ... as' deyilir: not as fast as (qədər sürətli deyil). Vacib qayda: bu quruluşda sifət öz əsas (dəyişməmiş) formasında qalır, ona '-er' əlavə olunmur.",
      form: "as + adjective + as  ·  not as + adjective + as",
      examples: [
        { en: "He is as tall as his brother.", note: "equal" },
        { en: "This phone is not as fast as the new one.", note: "not equal" },
        { en: "My coffee is as strong as yours.", note: "the adjective stays in base form" },
      ],
      pitfall: "Sifət bu quruluşda dəyişmir: 'as taller as' YOX -> 'as tall as'.",
    },
    {
      title: "Irregular comparatives and superlatives",
      level: "B1",
      explanation: "Some common adjectives have irregular forms that you must memorise: good/better/best, bad/worse/worst, far/further/furthest.",
      azNote: "Bəzi çox işlənən sifətlər müqayisə formalarını ümumi qaydaya görə düzəltmir, ona görə də onları olduğu kimi əzbərləmək lazımdır. Ən vaciblərini yadda saxla: good -> better -> the best (yaxşı -> daha yaxşı -> ən yaxşı), bad -> worse -> the worst (pis -> daha pis -> ən pis), far -> further -> the furthest (uzaq -> daha uzaq -> ən uzaq). Bu sifətlərə '-er' və ya 'more' əlavə edilmir.",
      form: "good -> better -> the best  ·  bad -> worse -> the worst  ·  far -> further -> the furthest",
      examples: [
        { en: "Her English is better than mine.", note: "good -> better" },
        { en: "This is the worst film I have ever seen.", note: "bad -> the worst" },
        { en: "The station is further than I thought.", note: "far -> further" },
      ],
      pitfall: "'gooder' və ya 'baddest' yoxdur. Düzgün: 'better' və 'the worst'.",
    },
    {
      title: "Comparative and superlative of adverbs",
      level: "B2",
      explanation: "Most adverbs ending in '-ly' use 'more' and 'the most'. Some short adverbs take '-er' and 'the ...-est'.",
      azNote: "Zərflərin (hərəkətin necə icra olunduğunu bildirən sözlərin) də müqayisə dərəcələri var. '-ly' ilə bitən zərflərin qarşısına 'more' və 'the most' qoyulur: carefully -> more carefully -> the most carefully. Bəzi qısa zərflər ('hard', 'fast') isə sifət kimi '-er' və 'the ...-est' alır: hard -> harder. Zərfi sifətlə qarışdırma: hərəkəti təsvir edəndə zərf (carefully), şeyi təsvir edəndə sifət (careful) işlənir.",
      form: "more + adverb + than  ·  the most + adverb  ·  short adverb + -er",
      examples: [
        { en: "Please drive more carefully than before.", note: "-ly adverb + more" },
        { en: "She finished the most quickly of everyone.", note: "the most + adverb" },
        { en: "He works harder than his colleagues.", note: "short adverb takes -er" },
      ],
      pitfall: "Zərfi sifətlə qarışdırma: 'more careful' (sifət) deyil, hərəkət üçün 'more carefully' (zərf).",
    },
    {
      title: "Modifying comparatives: much / far / a bit / slightly",
      level: "B2",
      explanation: "We use 'much', 'far', 'a lot' for a big difference and 'a bit', 'a little', 'slightly' for a small difference before a comparative.",
      azNote: "Comparative-in qarşısına söz əlavə edib fərqin nə qədər böyük və ya kiçik olduğunu göstərə bilərik. Böyük fərq üçün 'much', 'far' və ya 'a lot' işlədilir: much faster (xeyli sürətli). Kiçik fərq üçün isə 'a bit', 'a little' və ya 'slightly' qoyulur: a bit easier (bir az asan). Diqqət: 'very' sözü comparative ilə işlənmir; onun yerinə 'much' deyilir.",
      form: "much / far / a lot / a bit / slightly + comparative",
      examples: [
        { en: "This car is much faster than my old one.", note: "big difference" },
        { en: "The exam was a bit easier than last year.", note: "small difference" },
        { en: "She is slightly taller than her sister.", note: "small difference" },
      ],
      pitfall: "'very' comparativlə işlənmir: 'very faster' YOX -> 'much faster'.",
    },
    {
      title: "the + comparative, the + comparative",
      level: "C1",
      explanation: "This structure shows that two things change together: when one increases, the other changes too.",
      azNote: "Bu quruluş iki şeyin paralel, yəni birlikdə dəyişdiyini bildirir: biri artdıqca digəri də artır və ya azalır (məsələn, nə qədər çox məşq etsən, bir o qədər yaxşı olarsan). Cümlə iki hissədən ibarətdir və hər iki hissədə 'the + comparative' işlədilir: 'The more you practise, the better you get'. Vacib qayda: hər iki hissədə 'the' mütləq olmalıdır.",
      form: "The + comparative + clause, the + comparative + clause",
      examples: [
        { en: "The more you practise, the better you get.", note: "two changes linked together" },
        { en: "The harder she tried, the worse it became.", note: "with irregular forms" },
        { en: "The older we get, the wiser we become.", note: "both halves need 'the'" },
      ],
      pitfall: "Hər iki hissədə 'the' lazımdır: 'More you practise, better you get' YOX.",
    },
  ],
  practice: [
    {
      type: "multiple-choice",
      prompt: "This street is ___ than the old one.",
      options: ["more quiet", "quieter", "quietest"],
      answer: 1,
      explanation: "Short adjective takes '-er': 'quieter'. 'more quiet' is wrong and 'quietest' is superlative.",
    },
    {
      type: "gap-fill",
      prompt: "Mount Everest is the ___ mountain in the world. (high)",
      answer: "highest",
      explanation: "Superlative of the short adjective 'high' is 'highest' after 'the'.",
    },
    {
      type: "multiple-choice",
      prompt: "My new job is ___ interesting than my last one.",
      options: ["more", "most", "the most"],
      answer: 0,
      explanation: "'interesting' is a long adjective, so the comparative is 'more interesting than'.",
    },
    {
      type: "gap-fill",
      prompt: "He is not ___ tall ___ his father. (use the equality structure, write both words)",
      answer: "as tall as",
      explanation: "Equality structure 'as + adjective + as' becomes 'not as tall as' for inequality.",
    },
    {
      type: "multiple-choice",
      prompt: "Your handwriting is ___ than mine.",
      options: ["gooder", "more good", "better"],
      answer: 2,
      explanation: "'good' is irregular: the comparative is 'better'.",
    },
    {
      type: "gap-fill",
      prompt: "That was the ___ film I have ever seen. (bad, superlative)",
      answer: "worst",
      explanation: "'bad' is irregular: the superlative is 'the worst'.",
    },
    {
      type: "multiple-choice",
      prompt: "You should speak ___ so everyone understands.",
      options: ["more clearly", "more clear", "clearest"],
      answer: 0,
      explanation: "We modify the verb 'speak', so we need the adverb form 'more clearly'.",
    },
    {
      type: "gap-fill",
      prompt: "This laptop is ___ faster than my old one - a huge difference. (use a strong modifier, one word)",
      answer: "much",
      explanation: "For a big difference we use 'much' (or 'far') before the comparative.",
    },
    {
      type: "multiple-choice",
      prompt: "The more you read, ___ your vocabulary grows.",
      options: ["the bigger", "bigger", "more big"],
      answer: 0,
      explanation: "The structure 'the + comparative, the + comparative' needs 'the bigger' in the second part.",
    },
  ],
};
