import type { GrammarGroup } from "../types";

export const comparatives: GrammarGroup = {
  id: "comparatives",
  description: "Comparatives and superlatives let us compare two or more things by degree.",
  azDescription: "Müqayisə dərəcələri iki və ya daha çox şeyi keyfiyyət baxımından müqayisə etməyə imkan verir.",
  rules: [
    {
      title: "Comparative adjectives: short vs long",
      level: "B1",
      explanation: "Short adjectives take '-er'. Long adjectives (two or more syllables) use 'more'. We add 'than' to name the second thing.",
      azNote: "Qısa sifətlərə '-er' əlavə olunur, uzun sifətlərdən əvvəl 'more' işlənir. Müqayisə olunan ikinci şeydən əvvəl 'than' gəlir.",
      form: "short adjective + -er + than  ·  more + long adjective + than",
      examples: [
        { en: "My bag is cheaper than yours.", note: "short adjective + -er" },
        { en: "This book is more interesting than the film.", note: "long adjective + more" },
        { en: "Today is hotter than yesterday.", note: "double the final consonant: hot -> hotter" },
      ],
      pitfall: "'more cheaper' deyilmir. Ya '-er', ya da 'more' seç, ikisi birlikdə olmaz.",
    },
    {
      title: "Superlative adjectives: the -est / the most",
      level: "B1",
      explanation: "Superlatives compare one thing with a whole group. Short adjectives take 'the ...-est'; long adjectives take 'the most ...'.",
      azNote: "Superlativ bir şeyi bütöv bir qrupla müqayisə edir. Qısa sifət 'the ...-est', uzun sifət 'the most ...' alır. Əvvəlində 'the' vacibdir.",
      form: "the + short adjective + -est  ·  the most + long adjective",
      examples: [
        { en: "She is the tallest student in the class.", note: "short adjective + -est" },
        { en: "It was the most expensive meal of the trip.", note: "long adjective + most" },
        { en: "This is the easiest exercise in the book.", note: "y changes to i: easy -> easiest" },
      ],
      pitfall: "Superlativdən əvvəl 'the' düşür: 'most expensive' YOX -> 'the most expensive'.",
    },
    {
      title: "as ... as (equality) and not as ... as",
      level: "B1",
      explanation: "Use 'as + adjective + as' to say two things are equal. 'not as ... as' shows they are not equal.",
      azNote: "Bərabərlik üçün 'as + sifət + as' işlənir. Bərabər olmayanda 'not as ... as' deyilir, sifət dəyişmir.",
      form: "as + adjective + as  ·  not as + adjective + as",
      examples: [
        { en: "He is as tall as his brother.", note: "equal" },
        { en: "This phone is not as fast as the new one.", note: "not equal" },
        { en: "My coffee is as strong as yours.", note: "the adjective stays in base form" },
      ],
      pitfall: "Sifət bu quruluşda dəyişmir: 'as taller as' YOX -> 'as tall as'.",
    },
    {
      title: "Irregular comparatives and superlatives",
      level: "B1",
      explanation: "Some common adjectives have irregular forms that you must memorise: good/better/best, bad/worse/worst, far/further/furthest.",
      azNote: "Bəzi vacib sifətlərin qaydasız formaları var, onları əzbərlə: good/better/best, bad/worse/worst, far/further/furthest.",
      form: "good -> better -> the best  ·  bad -> worse -> the worst  ·  far -> further -> the furthest",
      examples: [
        { en: "Her English is better than mine.", note: "good -> better" },
        { en: "This is the worst film I have ever seen.", note: "bad -> the worst" },
        { en: "The station is further than I thought.", note: "far -> further" },
      ],
      pitfall: "'gooder' və ya 'baddest' yoxdur. Düzgün: 'better' və 'the worst'.",
    },
    {
      title: "Comparative and superlative of adverbs",
      level: "B2",
      explanation: "Most adverbs ending in '-ly' use 'more' and 'the most'. Some short adverbs take '-er' and 'the ...-est'.",
      azNote: "'-ly' ilə bitən zərflər 'more' və 'the most' alır. Bəzi qısa zərflər ('hard', 'fast') '-er' və 'the ...-est' qəbul edir.",
      form: "more + adverb + than  ·  the most + adverb  ·  short adverb + -er",
      examples: [
        { en: "Please drive more carefully than before.", note: "-ly adverb + more" },
        { en: "She finished the most quickly of everyone.", note: "the most + adverb" },
        { en: "He works harder than his colleagues.", note: "short adverb takes -er" },
      ],
      pitfall: "Zərfi sifətlə qarışdırma: 'more careful' (sifət) deyil, hərəkət üçün 'more carefully' (zərf).",
    },
    {
      title: "Modifying comparatives: much / far / a bit / slightly",
      level: "B2",
      explanation: "We use 'much', 'far', 'a lot' for a big difference and 'a bit', 'a little', 'slightly' for a small difference before a comparative.",
      azNote: "Böyük fərq üçün comparativdən əvvəl 'much', 'far', 'a lot'; kiçik fərq üçün 'a bit', 'a little', 'slightly' işlənir.",
      form: "much / far / a lot / a bit / slightly + comparative",
      examples: [
        { en: "This car is much faster than my old one.", note: "big difference" },
        { en: "The exam was a bit easier than last year.", note: "small difference" },
        { en: "She is slightly taller than her sister.", note: "small difference" },
      ],
      pitfall: "'very' comparativlə işlənmir: 'very faster' YOX -> 'much faster'.",
    },
    {
      title: "the + comparative, the + comparative",
      level: "C1",
      explanation: "This structure shows that two things change together: when one increases, the other changes too.",
      azNote: "Bu quruluş iki şeyin birlikdə dəyişdiyini göstərir: biri artdıqca, digəri də dəyişir. Hər iki hissədə 'the' işlənir.",
      form: "The + comparative + clause, the + comparative + clause",
      examples: [
        { en: "The more you practise, the better you get.", note: "two changes linked together" },
        { en: "The harder she tried, the worse it became.", note: "with irregular forms" },
        { en: "The older we get, the wiser we become.", note: "both halves need 'the'" },
      ],
      pitfall: "Hər iki hissədə 'the' lazımdır: 'More you practise, better you get' YOX.",
    },
  ],
  practice: [
    {
      type: "multiple-choice",
      prompt: "This street is ___ than the old one.",
      options: ["more quiet", "quieter", "quietest"],
      answer: 1,
      explanation: "Short adjective takes '-er': 'quieter'. 'more quiet' is wrong and 'quietest' is superlative.",
    },
    {
      type: "gap-fill",
      prompt: "Mount Everest is the ___ mountain in the world. (high)",
      answer: "highest",
      explanation: "Superlative of the short adjective 'high' is 'highest' after 'the'.",
    },
    {
      type: "multiple-choice",
      prompt: "My new job is ___ interesting than my last one.",
      options: ["more", "most", "the most"],
      answer: 0,
      explanation: "'interesting' is a long adjective, so the comparative is 'more interesting than'.",
    },
    {
      type: "gap-fill",
      prompt: "He is not ___ tall ___ his father. (use the equality structure, write both words)",
      answer: "as tall as",
      explanation: "Equality structure 'as + adjective + as' becomes 'not as tall as' for inequality.",
    },
    {
      type: "multiple-choice",
      prompt: "Your handwriting is ___ than mine.",
      options: ["gooder", "more good", "better"],
      answer: 2,
      explanation: "'good' is irregular: the comparative is 'better'.",
    },
    {
      type: "gap-fill",
      prompt: "That was the ___ film I have ever seen. (bad, superlative)",
      answer: "worst",
      explanation: "'bad' is irregular: the superlative is 'the worst'.",
    },
    {
      type: "multiple-choice",
      prompt: "You should speak ___ so everyone understands.",
      options: ["more clearly", "more clear", "clearest"],
      answer: 0,
      explanation: "We modify the verb 'speak', so we need the adverb form 'more clearly'.",
    },
    {
      type: "gap-fill",
      prompt: "This laptop is ___ faster than my old one - a huge difference. (use a strong modifier, one word)",
      answer: "much",
      explanation: "For a big difference we use 'much' (or 'far') before the comparative.",
    },
    {
      type: "multiple-choice",
      prompt: "The more you read, ___ your vocabulary grows.",
      options: ["the bigger", "bigger", "more big"],
      answer: 0,
      explanation: "The structure 'the + comparative, the + comparative' needs 'the bigger' in the second part.",
    },
  ],
};
