import type { GrammarGroup } from "../types";

export const phrasalVerbs: GrammarGroup = {
  id: "phrasal-verbs",
  description: "Phrasal verbs combine a verb with a particle, and the meaning is often idiomatic.",
  azDescription: "Phrasal feillər feil ilə hissəcikdən (particle) ibarətdir və mənası çox vaxt idiomatik olur.",
  rules: [
    {
      title: "What a phrasal verb is",
      level: "B1",
      explanation: "A phrasal verb is a verb plus a small particle (a preposition or adverb). The two words together create a new meaning that you often cannot guess from the verb alone. For example, 'give up' means 'quit', not 'give'.",
      azNote: "Phrasal feil = feil + kiçik hissəcik. Birlikdə yeni məna verir, məsələn 'give up' = tərk etmək.",
      form: "verb + particle (e.g. give + up = give up)",
      examples: [
        { en: "Don't give up; you are almost there.", note: "give up = quit" },
        { en: "I usually wake up at seven o'clock.", note: "wake up = stop sleeping" },
      ],
      pitfall: "Hissəciyin mənasını ayrıca tərcümə etmə; bütöv ifadəni öyrən.",
    },
    {
      title: "Transitive separable phrasal verbs",
      level: "B2",
      explanation: "Many phrasal verbs take an object and can be separated. The noun object can go before or after the particle, but a pronoun object MUST go in the middle, between the verb and the particle.",
      azNote: "Ayrılan phrasal feillərdə isim hər iki yerdə dura bilər, amma əvəzlik (it, them) MÜTLƏQ ortada olur.",
      form: "verb + object + particle / verb + particle + object (pronoun always in the middle)",
      examples: [
        { en: "Please turn off the light.", note: "noun after the particle" },
        { en: "Please turn the light off.", note: "noun before the particle, also correct" },
        { en: "Please turn it off.", note: "pronoun must go in the middle" },
      ],
      pitfall: "'Turn off it' yanlışdır. Düzgünü: 'turn it off'.",
    },
    {
      title: "Transitive inseparable phrasal verbs",
      level: "B2",
      explanation: "Some phrasal verbs take an object but can never be split. The object, whether a noun or a pronoun, always comes after the whole phrasal verb.",
      azNote: "Ayrılmayan phrasal feillərdə obyekt (isim və ya əvəzlik) həmişə feildən SONRA gəlir; bölünmür.",
      form: "verb + particle + object (never split)",
      examples: [
        { en: "I look after the kids on Saturdays.", note: "look after = take care of" },
        { en: "I look after them on Saturdays.", note: "pronoun still comes after, not in the middle" },
      ],
      pitfall: "'Look them after' yanlışdır. Düzgünü: 'look after them'.",
    },
    {
      title: "Intransitive phrasal verbs",
      level: "B2",
      explanation: "Intransitive phrasal verbs have no object at all. The verb and the particle stay together and nothing comes between them.",
      azNote: "Bəzi phrasal feillərin obyekti yoxdur. Feil və hissəcik birlikdə qalır, ortaya heç nə girmir.",
      form: "verb + particle (no object)",
      examples: [
        { en: "My car broke down on the motorway.", note: "break down = stop working" },
        { en: "The plane took off on time.", note: "take off = leave the ground" },
        { en: "I grew up in a small town.", note: "grow up = become an adult" },
      ],
      pitfall: "Bu feillərə obyekt əlavə etmə; məsələn 'break down' obyekt qəbul etmir.",
    },
    {
      title: "Three-part phrasal verbs",
      level: "B2",
      explanation: "Three-part (or three-word) phrasal verbs have a verb plus two particles. They are inseparable, and the object always comes after the second particle.",
      azNote: "Üç hissəli phrasal feillər: feil + iki hissəcik. Bölünmür, obyekt sonda gəlir.",
      form: "verb + particle + particle + object",
      examples: [
        { en: "I look forward to the weekend.", note: "look forward to = feel excited about" },
        { en: "I can't put up with this noise.", note: "put up with = tolerate" },
        { en: "She gets on with her colleagues.", note: "get on with = have a good relationship" },
      ],
      pitfall: "'Look forward to' sonrasında feil gələrsə, '-ing' işlənir: 'look forward to seeing you'.",
    },
    {
      title: "Common phrasal verbs to know",
      level: "B1",
      explanation: "Here is a useful set of everyday phrasal verbs: give up (quit), find out (discover), carry on (continue), set up (start or arrange), and work out (solve or exercise). Learn them as whole units.",
      azNote: "Faydalı phrasal feillər: give up (tərk etmək), find out (öyrənmək), carry on (davam etmək), set up (qurmaq), work out (həll etmək).",
      form: "common verbs: give up, find out, carry on, set up, work out",
      examples: [
        { en: "I want to find out the truth.", note: "find out = discover" },
        { en: "They set up a new company last year.", note: "set up = start or establish" },
        { en: "Let's carry on with the lesson.", note: "carry on = continue" },
      ],
      pitfall: "Bu ifadələri tək söz kimi əzbərlə; mənaları feilin öz mənasından fərqlidir.",
    },
  ],
  practice: [
    {
      type: "multiple-choice",
      prompt: "Choose the correct sentence with a pronoun:",
      options: ["Turn off it.", "Turn it off.", "Turn it off down."],
      answer: 1,
      explanation: "This is a separable phrasal verb, so a pronoun must go in the middle: 'turn it off'.",
    },
    {
      type: "gap-fill",
      prompt: "I need to ___ out what time the train leaves. (discover)",
      answer: "find",
      explanation: "'find out' means to discover information.",
    },
    {
      type: "multiple-choice",
      prompt: "Which sentence uses an inseparable phrasal verb correctly?",
      options: ["I look the kids after.", "I look after them.", "I look them after."],
      answer: 1,
      explanation: "'look after' is inseparable, so the object always comes after it: 'look after them'.",
    },
    {
      type: "gap-fill",
      prompt: "My car broke ___ on the way to work. (stopped working)",
      answer: "down",
      explanation: "'break down' means to stop working; it is an intransitive phrasal verb.",
    },
    {
      type: "multiple-choice",
      prompt: "Complete: 'I can't put up ___ this noise.'",
      options: ["with", "to", "for"],
      answer: 0,
      explanation: "The three-part phrasal verb is 'put up with', meaning to tolerate.",
    },
    {
      type: "gap-fill",
      prompt: "Don't ___ up! You can finish the race. (quit)",
      answer: "give",
      explanation: "'give up' means to quit or stop trying.",
    },
    {
      type: "multiple-choice",
      prompt: "Which sentence is correct?",
      options: ["Look forward to see you.", "Look forward to seeing you.", "Look forward see you."],
      answer: 1,
      explanation: "After 'look forward to' we use the -ing form: 'look forward to seeing you'.",
    },
    {
      type: "gap-fill",
      prompt: "The plane took ___ ten minutes late. (left the ground)",
      answer: "off",
      explanation: "'take off' means a plane leaves the ground; it has no object here.",
    },
  ],
};
