import type { GrammarGroup } from "../types";

export const quantifiers: GrammarGroup = {
  id: "quantifiers",
  description: "Quantifiers tell us how much or how many. The right choice depends on whether the noun is countable or uncountable.",
  azDescription: "Kemiyyet bildirenler ne qeder ve ya neceyi gosterir. Duzgun secim ismin sayila bilen ve ya sayila bilmeyen olmasindan asilidir.",
  rules: [
    {
      title: "Countable vs uncountable nouns",
      level: "B1",
      explanation: "Countable nouns have singular and plural forms and can take 'a/an'. Uncountable nouns have no plural and do not take 'a/an'.",
      azNote: "Sayila bilen isimlerin cemi var ve 'a/an' alir. Sayila bilmeyenlerin cemi yoxdur, 'a/an' almir.",
      form: "countable: a book / two books  ·  uncountable: water (no plural, no 'a')",
      examples: [
        { en: "I bought an apple and three bananas.", note: "countable nouns" },
        { en: "She gave me some advice and information.", note: "uncountable, no plural -s" },
      ],
      pitfall: "'information', 'advice', 'money' sayila bilmir: 'informations' demek olmaz.",
    },
    {
      title: "some vs any",
      level: "B1",
      explanation: "Use 'some' in affirmative sentences and 'any' in negatives and most questions. Use 'some' in offers and requests.",
      azNote: "Tesdiq cumlede 'some', inkar ve suallarda 'any'. Teklif ve xahisde yene 'some'.",
      form: "some + plural/uncountable  ·  any + plural/uncountable",
      examples: [
        { en: "There are some eggs in the fridge.", note: "affirmative" },
        { en: "I do not have any money right now.", note: "negative" },
        { en: "Would you like some tea?", note: "offer uses some" },
      ],
      pitfall: "Inkarda 'some' yox, 'any' islet: 'I do not have any time'.",
    },
    {
      title: "much / many / a lot of / lots of",
      level: "B1",
      explanation: "Use 'many' with countable plurals and 'much' with uncountable nouns, mostly in negatives and questions. 'a lot of' and 'lots of' work with both.",
      azNote: "'many' sayila bilenlerle, 'much' sayila bilmeyenlerle (cox vaxt inkar/sualda). 'a lot of' her ikisi ile islenir.",
      form: "many + countable  ·  much + uncountable  ·  a lot of / lots of + both",
      examples: [
        { en: "How many friends do you have?", note: "countable question" },
        { en: "There is not much sugar left.", note: "uncountable negative" },
        { en: "We have a lot of work today.", note: "a lot of with uncountable" },
      ],
      pitfall: "Tesdiq cumlede 'much' qariib seslenir: 'a lot of' de.",
    },
    {
      title: "(a) few vs (a) little",
      level: "B2",
      explanation: "'a few' and 'a little' mean a small but positive amount. 'few' and 'little' (no 'a') mean almost none, with a negative feeling.",
      azNote: "'a few/a little' = az amma kifayet. 'few/little' = demek olar hec, menfi cahetden.",
      form: "(a) few + countable plural  ·  (a) little + uncountable",
      examples: [
        { en: "I have a few questions for you.", note: "countable, positive" },
        { en: "There is a little milk in the cup.", note: "uncountable, positive" },
        { en: "Few people came, so it was quiet.", note: "without 'a', means almost none" },
      ],
      pitfall: "'a' itse mena deyisir: 'little money' = demek olar pulsuz.",
    },
    {
      title: "all / every / each",
      level: "B2",
      explanation: "'all' takes a plural or uncountable noun. 'every' and 'each' take a singular noun; 'each' stresses individuals one by one.",
      azNote: "'all' cem/sayila bilmeyenle. 'every' ve 'each' tek isimle; 'each' her ferdi ayri-ayri vurgulayir.",
      form: "all + plural/uncountable  ·  every / each + singular noun",
      examples: [
        { en: "All students passed the exam.", note: "all + plural" },
        { en: "Every room has a window.", note: "every + singular" },
        { en: "Each child got a present.", note: "each stresses individuals" },
      ],
      pitfall: "'every' ve 'each'-den sonra tek isim ve tek feil: 'every room has', 'every rooms' yox.",
    },
    {
      title: "both / either / neither",
      level: "B2",
      explanation: "'both' means the two together. 'either' means one or the other. 'neither' means not one and not the other.",
      azNote: "'both' = ikisi de. 'either' = biri ve ya digeri. 'neither' = hec biri.",
      form: "both + plural  ·  either / neither + singular noun and verb",
      examples: [
        { en: "Both answers are correct.", note: "both + plural verb" },
        { en: "You can take either road.", note: "either, one of two" },
        { en: "Neither option works for me.", note: "neither + singular verb" },
      ],
      pitfall: "'neither' ozu menfidir: 'neither is good', 'neither is not good' yox.",
    },
    {
      title: "too much/many vs (not) enough",
      level: "B2",
      explanation: "'too much' and 'too many' mean more than needed. 'enough' means the right amount; 'not enough' means less than needed.",
      azNote: "'too much/many' = lazim olandan cox. 'enough' = kifayet; 'not enough' = catismir.",
      form: "too much + uncountable  ·  too many + countable  ·  enough + noun",
      examples: [
        { en: "There is too much noise here.", note: "too much + uncountable" },
        { en: "You made too many mistakes.", note: "too many + countable" },
        { en: "We do not have enough chairs.", note: "not enough = too few" },
      ],
      pitfall: "'enough' isimden evvel gelir: 'enough money', amma sifetden sonra: 'big enough'.",
    },
  ],
  practice: [
    {
      type: "multiple-choice",
      prompt: "There isn't ___ milk left in the bottle.",
      options: ["many", "much", "few"],
      answer: 1,
      explanation: "'milk' is uncountable, so use 'much' in a negative sentence.",
    },
    {
      type: "gap-fill",
      prompt: "I have a ___ questions before we start. (small but positive number)",
      answer: "few",
      explanation: "'questions' is countable and the meaning is positive, so use 'a few'.",
    },
    {
      type: "multiple-choice",
      prompt: "Would you like ___ coffee?",
      options: ["any", "some", "many"],
      answer: 1,
      explanation: "Offers use 'some' even though the sentence is a question.",
    },
    {
      type: "gap-fill",
      prompt: "We don't have ___ time, so let's hurry. (uncountable, negative)",
      answer: "any",
      explanation: "Negative sentence with uncountable noun takes 'any'.",
    },
    {
      type: "multiple-choice",
      prompt: "___ student in the class has a laptop.",
      options: ["Every", "All", "Both"],
      answer: 0,
      explanation: "'Every' takes a singular noun and a singular verb, which fits 'student has'.",
    },
    {
      type: "gap-fill",
      prompt: "There is too ___ noise here; I can't think. (uncountable)",
      answer: "much",
      explanation: "'noise' is uncountable, so use 'too much'.",
    },
    {
      type: "multiple-choice",
      prompt: "___ answers are correct, so you get full marks.",
      options: ["Either", "Neither", "Both"],
      answer: 2,
      explanation: "'Both' means the two together and takes a plural noun and verb.",
    },
    {
      type: "gap-fill",
      prompt: "We don't have ___ chairs for all the guests. (not the right amount)",
      answer: "enough",
      explanation: "'not enough' means less than needed.",
    },
  ],
};
