import type { GrammarGroup } from "../types";

export const quantifiers: GrammarGroup = {
  id: "quantifiers",
  description: "Quantifiers tell us how much or how many. The right choice depends on whether the noun is countable or uncountable.",
  azDescription: "Kəmiyyət bildirən sözlər (quantifiers) bir şeyin nə qədər və ya neçə ədəd olduğunu bildirir. Hansını seçəcəyin ismin növündən asılıdır: sayıla bilən isimlər (countable - dənə-dənə saya bildiyimiz şeylər: book, apple) və sayıla bilməyən isimlər (uncountable - maye, toz kimi saya bilmədiyimiz şeylər: water, advice). Bəzi sözlər yalnız biri ilə, bəziləri isə hər ikisi ilə işlənir, ona görə əvvəlcə ismin növünü müəyyən etmək lazımdır.",
  rules: [
    {
      title: "Countable vs uncountable nouns",
      level: "B1",
      explanation: "Countable nouns have singular and plural forms and can take 'a/an'. Uncountable nouns have no plural and do not take 'a/an'.",
      azNote: "Sayıla bilən isimlər (countable) tək və cəm formada ola bilir və qarşılarında 'a/an' işlədə bilirik (a book - one book, two books). Sayıla bilməyən isimlərin (uncountable) isə cəm forması yoxdur və 'a/an' qəbul etmir, çünki onları ədədlə saya bilmirik (water, money). Buna görə hər yeni sözdə onun hansı qrupa aid olduğunu soruşmaq vacibdir.",
      form: "countable: a book / two books  ·  uncountable: water (no plural, no 'a')",
      examples: [
        { en: "I bought an apple and three bananas.", note: "countable nouns" },
        { en: "She gave me some advice and information.", note: "uncountable, no plural -s" },
      ],
      pitfall: "'information', 'advice', 'money' sayıla bilmir: 'informations' demək olmaz.",
    },
    {
      title: "some vs any",
      level: "B1",
      explanation: "Use 'some' in affirmative sentences and 'any' in negatives and most questions. Use 'some' in offers and requests.",
      azNote: "Təsdiq (müsbət) cümlələrdə 'some' işlədirik (There are some eggs). İnkar cümlələrdə və adi suallarda isə 'any' gəlir (I do not have any money / Do you have any money?). Lakin nəsə təklif edəndə və ya nəzakətlə xahiş edəndə sual olsa belə yenə 'some' işlətmək təbiidir, çünki burada cavabın 'hə' olacağını gözləyirik (Would you like some tea?).",
      form: "some + plural/uncountable  ·  any + plural/uncountable",
      examples: [
        { en: "There are some eggs in the fridge.", note: "affirmative" },
        { en: "I do not have any money right now.", note: "negative" },
        { en: "Would you like some tea?", note: "offer uses some" },
      ],
      pitfall: "İnkarda 'some' yox, 'any' işlət: 'I do not have any time'.",
    },
    {
      title: "much / many / a lot of / lots of",
      level: "B1",
      explanation: "Use 'many' with countable plurals and 'much' with uncountable nouns, mostly in negatives and questions. 'a lot of' and 'lots of' work with both.",
      azNote: "'many' sözünü sayıla bilən cəm isimlərlə işlədirik (many friends), 'much' sözünü isə sayıla bilməyən isimlərlə (much sugar). Hər ikisi daha çox inkar və sual cümlələrində gəlir. Müsbət cümlədə 'much/many' bir qədər qəribə səslənir, ona görə həm sayıla bilən, həm də sayıla bilməyən isimlərlə işləyən 'a lot of' və ya 'lots of' işlətmək daha təbiidir (We have a lot of work).",
      form: "many + countable  ·  much + uncountable  ·  a lot of / lots of + both",
      examples: [
        { en: "How many friends do you have?", note: "countable question" },
        { en: "There is not much sugar left.", note: "uncountable negative" },
        { en: "We have a lot of work today.", note: "a lot of with uncountable" },
      ],
      pitfall: "Təsdiq cümlədə 'much' qəribə səslənir: 'a lot of' de.",
    },
    {
      title: "(a) few vs (a) little",
      level: "B2",
      explanation: "'a few' and 'a little' mean a small but positive amount. 'few' and 'little' (no 'a') mean almost none, with a negative feeling.",
      azNote: "'a few' (sayıla bilənlərlə: a few questions) və 'a little' (sayıla bilməyənlərlə: a little milk) 'az, amma kifayət qədər var' mənasını verir - müsbət çalar daşıyır. 'a' artikli düşəndə isə məna dəyişir: 'few' və 'little' 'demək olar ki, heç yoxdur, çatışmır' deməkdir və mənfi çalar verir (Few people came = çox az adam gəldi). Yəni kiçik 'a' sözün mənasını tamamilə çevirir.",
      form: "(a) few + countable plural  ·  (a) little + uncountable",
      examples: [
        { en: "I have a few questions for you.", note: "countable, positive" },
        { en: "There is a little milk in the cup.", note: "uncountable, positive" },
        { en: "Few people came, so it was quiet.", note: "without 'a', means almost none" },
      ],
      pitfall: "'a' itsə məna dəyişir: 'little money' = demək olar pulsuz.",
    },
    {
      title: "all / every / each",
      level: "B2",
      explanation: "'all' takes a plural or uncountable noun. 'every' and 'each' take a singular noun; 'each' stresses individuals one by one.",
      azNote: "'all' (hamısı/bütün) cəm və ya sayıla bilməyən isimlərlə işlənir (all students, all water). 'every' və 'each' (hər) isə tək isim və tək feillə işlənir (every room has, each child got) - 'every rooms' demək olmaz. Fərq incədir: 'every' qrupun hamısını bir bütöv kimi nəzərdə tutur, 'each' isə hər fərdi ayrı-ayrılıqda, bir-bir vurğulayır.",
      form: "all + plural/uncountable  ·  every / each + singular noun",
      examples: [
        { en: "All students passed the exam.", note: "all + plural" },
        { en: "Every room has a window.", note: "every + singular" },
        { en: "Each child got a present.", note: "each stresses individuals" },
      ],
      pitfall: "'every' və 'each'-dən sonra tək isim və tək feil: 'every room has', 'every rooms' yox.",
    },
    {
      title: "both / either / neither",
      level: "B2",
      explanation: "'both' means the two together. 'either' means one or the other. 'neither' means not one and not the other.",
      azNote: "Bu üç söz iki şey haqqında danışanda işlənir. 'both' = ikisi də birlikdə (cəm isim və cəm feil ilə: Both answers are correct). 'either' = ikisindən biri, fərqi yoxdur hansı (tək isimlə: either road). 'neither' = ikisindən heç biri (tək isimlə: neither option). Diqqət: 'neither' sözünün özü artıq inkar mənası daşıyır, ona görə cümlədə ikinci dəfə 'not' işlətmirik (neither is good - doğru, neither is not good - səhv).",
      form: "both + plural  ·  either / neither + singular noun and verb",
      examples: [
        { en: "Both answers are correct.", note: "both + plural verb" },
        { en: "You can take either road.", note: "either, one of two" },
        { en: "Neither option works for me.", note: "neither + singular verb" },
      ],
      pitfall: "'neither' özü mənfidir: 'neither is good', 'neither is not good' yox.",
    },
    {
      title: "too much/many vs (not) enough",
      level: "B2",
      explanation: "'too much' and 'too many' mean more than needed. 'enough' means the right amount; 'not enough' means less than needed.",
      azNote: "'too much' (sayıla bilməyənlərlə: too much noise) və 'too many' (sayıla bilənlərlə: too many mistakes) 'lazım olandan artıq, həddən çox' deməkdir və mənfi məna daşıyır. 'enough' isə 'kifayət qədər, tam lazım olduğu qədər' deməkdir; 'not enough' isə 'çatışmır, az gəlir' (not enough chairs). Yadda saxla: 'enough' isimdən əvvəl gəlir (enough money), amma sifətdən sonra gəlir (big enough).",
      form: "too much + uncountable  ·  too many + countable  ·  enough + noun",
      examples: [
        { en: "There is too much noise here.", note: "too much + uncountable" },
        { en: "You made too many mistakes.", note: "too many + countable" },
        { en: "We do not have enough chairs.", note: "not enough = too few" },
      ],
      pitfall: "'enough' isimdən əvvəl gəlir: 'enough money', amma sifətdən sonra: 'big enough'.",
    },
  ],
  practice: [
    {
      type: "multiple-choice",
      prompt: "There isn't ___ milk left in the bottle.",
      options: ["many", "much", "few"],
      answer: 1,
      explanation: "'milk' is uncountable, so use 'much' in a negative sentence.",
    },
    {
      type: "gap-fill",
      prompt: "I have a ___ questions before we start. (small but positive number)",
      answer: "few",
      explanation: "'questions' is countable and the meaning is positive, so use 'a few'.",
    },
    {
      type: "multiple-choice",
      prompt: "Would you like ___ coffee?",
      options: ["any", "some", "many"],
      answer: 1,
      explanation: "Offers use 'some' even though the sentence is a question.",
    },
    {
      type: "gap-fill",
      prompt: "We don't have ___ time, so let's hurry. (uncountable, negative)",
      answer: "any",
      explanation: "Negative sentence with uncountable noun takes 'any'.",
    },
    {
      type: "multiple-choice",
      prompt: "___ student in the class has a laptop.",
      options: ["Every", "All", "Both"],
      answer: 0,
      explanation: "'Every' takes a singular noun and a singular verb, which fits 'student has'.",
    },
    {
      type: "gap-fill",
      prompt: "There is too ___ noise here; I can't think. (uncountable)",
      answer: "much",
      explanation: "'noise' is uncountable, so use 'too much'.",
    },
    {
      type: "multiple-choice",
      prompt: "___ answers are correct, so you get full marks.",
      options: ["Either", "Neither", "Both"],
      answer: 2,
      explanation: "'Both' means the two together and takes a plural noun and verb.",
    },
    {
      type: "gap-fill",
      prompt: "We don't have ___ chairs for all the guests. (not the right amount)",
      answer: "enough",
      explanation: "'not enough' means less than needed.",
    },
  ],
};
