import type { ConnectorGroup } from "../types";

export const addition: ConnectorGroup = {
  id: "addition",
  description: "Use these to add one more idea, fact, or argument on top of what you have already said.",
  azDescription: "Dediyin fikrin üstünə bir fikir də əlavə edəndə işlədilir.",
  connectors: [
    {
      phrase: "also",
      level: "B1",
      meaning: "in addition; as well",
      example: "She speaks French, and she also speaks a little Italian.",
      register: "neutral",
      position: "Usually before the main verb (or after 'be').",
      synonyms: ["too", "as well"],
      azNote: "Cümlənin ortasında, əsas feildən əvvəl gəlir: 'She also works here.'",
    },
    {
      phrase: "too",
      level: "B1",
      meaning: "also; in addition",
      example: "I was tired, and I was hungry too.",
      register: "informal",
      position: "Usually at the end of the sentence.",
      synonyms: ["also", "as well"],
      pitfall: "'too' cümlə sonunda, 'also' ortada gəlir.",
      azNote: "Cümlənin sonunda işlənir.",
    },
    {
      phrase: "as well as",
      level: "B1",
      meaning: "in addition to (something)",
      example: "The course teaches grammar as well as pronunciation.",
      register: "neutral",
      position: "Connects two nouns/verbs inside one sentence.",
      pitfall: "Feildən sonra -ing gəlir: 'as well as teaching', NOT 'as well as to teach'.",
      azNote: "İki şeyi bir cümlədə birləşdirir.",
    },
    {
      phrase: "in addition",
      level: "B2",
      meaning: "used to add a further point",
      example: "The hotel is cheap. In addition, it is very close to the beach.",
      register: "formal",
      position: "Sentence start, followed by a comma.",
      synonyms: ["moreover", "furthermore"],
      pitfall: "'In addition' (vergül) ≠ 'in addition TO' (isim ilə). 'In addition to the price...'",
      azNote: "Cümlə başında, sonra vergül.",
    },
    {
      phrase: "moreover",
      level: "B2",
      meaning: "and also, more importantly",
      example: "The plan is expensive. Moreover, it may not even work.",
      register: "formal",
      position: "Sentence start, followed by a comma.",
      synonyms: ["furthermore", "in addition"],
      azNote: "Daha güclü/rəsmi əlavə — adətən yazıda.",
    },
    {
      phrase: "furthermore",
      level: "C1",
      meaning: "in addition to what has been said (often a stronger point)",
      example: "The results were inconclusive. Furthermore, the sample was too small to draw conclusions.",
      register: "academic",
      position: "Sentence start, followed by a comma.",
      synonyms: ["moreover", "in addition"],
      azNote: "Akademik/esse yazısı üçün ideal.",
    },
    {
      phrase: "what's more",
      level: "B2",
      meaning: "and also (adds a surprising or stronger point)",
      example: "The food was delicious, and what's more, it was free.",
      register: "informal",
      position: "Sentence start or after a comma.",
      synonyms: ["moreover", "on top of that"],
      azNote: "Danışıqda / qeyri-rəsmi yazıda — 'üstəlik'.",
    },
    {
      phrase: "not only ... but also",
      level: "B2",
      meaning: "used to add a second, often more impressive, point",
      example: "He is not only a talented writer but also a successful teacher.",
      register: "neutral",
      position: "Wraps around the two things being added.",
      pitfall: "Cümlə başında 'Not only' gələrsə, köməkçi feil çevrilir: 'Not only IS he...'",
      azNote: "İki tərəfi balanslı saxla: 'not only [isim] but also [isim]'.",
    },
  ],
  practice: [
    {
      type: "gap-fill",
      prompt: "The flat is modern. In ___, it has a great view of the park.",
      answer: "addition",
      explanation: "'In addition,' adds a further point at the start of a sentence.",
    },
    {
      type: "multiple-choice",
      prompt: "Which word goes at the END of a sentence?",
      options: ["also", "moreover", "too", "furthermore"],
      answer: 2,
      explanation: "'too' typically comes at the end: 'I'm coming too.'",
    },
    {
      type: "multiple-choice",
      prompt: "Choose the most ACADEMIC connector for an essay:",
      options: ["what's more", "too", "furthermore", "and"],
      answer: 2,
      explanation: "'Furthermore' is formal/academic; 'what's more' is informal.",
    },
    {
      type: "gap-fill",
      prompt: "She not only sings ___ also writes her own songs.",
      answer: "but",
      explanation: "The structure is 'not only ... but also ...'.",
    },
    {
      type: "multiple-choice",
      prompt: "Which sentence is correct?",
      options: [
        "As well as to teach, she writes books.",
        "As well as teaching, she writes books.",
        "As well teaching, she writes books.",
        "As well as teach, she writes books.",
      ],
      answer: 1,
      explanation: "After 'as well as' use the -ing form: 'as well as teaching'.",
    },
  ],
};
