import type { ConnectorGroup } from "../types";

export const attribution: ConnectorGroup = {
  id: "attribution",
  description: "Use these to report what other people say or believe — common in argument essays.",
  azDescription: "Başqalarının nə dediyini/düşündüyünü çatdıranda — esse yazısında çox işlənir.",
  connectors: [
    {
      phrase: "some people say (that)",
      level: "B1",
      meaning: "used to report a common opinion",
      example: "Some people say that money brings happiness.",
      register: "neutral",
      position: "Sentence start, before a clause.",
      synonyms: ["some people believe", "some argue"],
      azNote: "Ümumi bir fikri təqdim etmək — 'bəziləri deyir ki'.",
    },
    {
      phrase: "some people claim (that)",
      level: "B2",
      meaning: "used to report an opinion you may not fully accept",
      example: "Some people claim that technology makes us lazy.",
      register: "neutral",
      position: "Sentence start, before a clause.",
      synonyms: ["it is claimed that", "some argue"],
      pitfall: "'claim' fikrin doğruluğuna şübhə qatır — neytral üçün 'say' işlət.",
      azNote: "Razı olmaya biləcəyin fikir — 'bəziləri iddia edir ki'.",
    },
    {
      phrase: "it is often said that",
      level: "B2",
      meaning: "used to report a widely repeated idea",
      example: "It is often said that first impressions matter most.",
      register: "formal",
      position: "Sentence start, before a clause.",
      synonyms: ["it is widely believed that"],
      azNote: "Geniş yayılmış fikir — 'çox vaxt deyilir ki'.",
    },
    {
      phrase: "it is widely believed that",
      level: "C1",
      meaning: "used to report a belief held by many people",
      example: "It is widely believed that exercise reduces stress.",
      register: "academic",
      position: "Sentence start, before a clause.",
      synonyms: ["it is generally accepted that"],
      azNote: "Akademik — 'geniş şəkildə inanılır ki'.",
    },
    {
      phrase: "according to",
      level: "B2",
      meaning: "as stated by a person or source",
      example: "According to the report, sales rose by 10%.",
      register: "neutral",
      position: "Sentence start (comma after) or mid-sentence; followed by a noun.",
      pitfall: "'According to me' YANLIŞdır — öz fikrin üçün 'in my opinion' işlət.",
      azNote: "Mənbəyə istinad — ardınca isim. ('according to me' İŞLƏNMİR!)",
    },
    {
      phrase: "critics argue that",
      level: "C1",
      meaning: "used to report an opposing or critical view",
      example: "Critics argue that the policy harms small businesses.",
      register: "academic",
      position: "Sentence start, before a clause.",
      synonyms: ["opponents claim that", "it has been argued that"],
      azNote: "Əks/tənqidi mövqe — 'tənqidçilər iddia edir ki'.",
    },
  ],
  practice: [
    {
      type: "multiple-choice",
      prompt: "Which is WRONG?",
      options: [
        "According to the news, it will rain.",
        "According to scientists, the climate is changing.",
        "According to me, the film was great.",
        "According to the report, profits fell.",
      ],
      answer: 2,
      explanation: "Never say 'according to me' — use 'in my opinion' for your own view.",
    },
    {
      type: "gap-fill",
      prompt: "Some people ___ that social media harms teenagers. (report an arguable opinion, one word)",
      answer: "claim",
      accept: ["say", "argue", "believe"],
      explanation: "'claim/argue/say that' report what others think.",
    },
    {
      type: "gap-fill",
      prompt: "___ to the survey, most users prefer the app. (one word)",
      answer: "according",
      explanation: "'According to' cites a source and is followed by a noun.",
    },
    {
      type: "multiple-choice",
      prompt: "Which best introduces an OPPOSING expert view in an essay?",
      options: ["in my opinion", "critics argue that", "for example", "of course"],
      answer: 1,
      explanation: "'Critics argue that' presents a critical/opposing view.",
    },
  ],
};
