import type { ConnectorGroup } from "../types";

export const attribution: ConnectorGroup = {
  id: "attribution",
  description: "Use these to report what other people say or believe — common in argument essays.",
  azDescription: "Başqalarının nə dediyini/düşündüyünü çatdıranda — esse yazısında çox işlənir.",
  connectors: [
    {
      phrase: "some people say (that)",
      level: "B1",
      meaning: "used to report a common opinion",
      azMeaning: "bəziləri deyir ki",
      example: "Some people say that money brings happiness.",
      register: "neutral",
      position: "Sentence start, before a clause.",
      synonyms: ["some people believe", "some argue"],
    },
    {
      phrase: "some people claim (that)",
      level: "B2",
      meaning: "used to report an opinion you may not fully accept",
      azMeaning: "bəziləri iddia edir ki",
      example: "Some people claim that technology makes us lazy.",
      register: "neutral",
      position: "Sentence start, before a clause.",
      synonyms: ["it is claimed that", "some argue"],
      pitfall: "'claim' fikrin doğruluğuna şübhə qatır — neytral üçün 'say' işlət.",
    },
    {
      phrase: "it is often said that",
      level: "B2",
      meaning: "used to report a widely repeated idea",
      azMeaning: "çox vaxt deyilir ki",
      example: "It is often said that first impressions matter most.",
      register: "formal",
      position: "Sentence start, before a clause.",
      synonyms: ["it is widely believed that"],
    },
    {
      phrase: "it is widely believed that",
      level: "C1",
      meaning: "used to report a belief held by many people",
      azMeaning: "geniş şəkildə inanılır ki",
      example: "It is widely believed that exercise reduces stress.",
      register: "academic",
      position: "Sentence start, before a clause.",
      synonyms: ["it is generally accepted that"],
    },
    {
      phrase: "according to",
      level: "B2",
      meaning: "as stated by a person or source",
      azMeaning: "-ə görə, ...-in dediyinə görə",
      example: "According to the report, sales rose by 10%.",
      register: "neutral",
      position: "Sentence start (comma after) or mid-sentence; followed by a noun.",
      pitfall: "'According to me' YANLIŞdır — öz fikrin üçün 'in my opinion' işlət.",
    },
    {
      phrase: "critics argue that",
      level: "C1",
      meaning: "used to report an opposing or critical view",
      azMeaning: "tənqidçilər iddia edir ki",
      example: "Critics argue that the policy harms small businesses.",
      register: "academic",
      position: "Sentence start, before a clause.",
      synonyms: ["opponents claim that", "it has been argued that"],
    },
    {
      phrase: "research shows that",
      level: "B2",
      meaning: "used to support a point with research",
      azMeaning: "tədqiqatlar göstərir ki",
      example: "Research shows that sleep improves memory.",
      register: "neutral",
      position: "Sentence start, before a clause.",
      synonyms: ["studies show that"],
    },
    {
      phrase: "studies suggest that",
      level: "B2",
      meaning: "used to report a careful, less certain finding",
      azMeaning: "araşdırmalar göstərir ki",
      example: "Studies suggest that exercise reduces stress.",
      register: "academic",
      position: "Sentence start, before a clause.",
    },
    {
      phrase: "experts believe that",
      level: "B2",
      meaning: "used to report a view held by specialists",
      azMeaning: "ekspertlər hesab edir ki",
      example: "Experts believe that the climate is changing fast.",
      register: "neutral",
      position: "Sentence start, before a clause.",
    },
    {
      phrase: "it could be argued that",
      level: "C1",
      meaning: "used to introduce a possible argument carefully",
      azMeaning: "iddia etmək olar ki",
      example: "It could be argued that the law is now outdated.",
      register: "academic",
      position: "Sentence start, before a clause.",
    },
    {
      phrase: "it is generally agreed that",
      level: "C1",
      meaning: "used to report a widely shared view",
      azMeaning: "ümumən qəbul edilir ki",
      example: "It is generally agreed that smoking is harmful.",
      register: "academic",
      position: "Sentence start, before a clause.",
    },
    {
      phrase: "as ... points out",
      level: "C1",
      meaning: "used to refer to what a person or source says",
      azMeaning: "...-in qeyd etdiyi kimi",
      example: "As the author points out, the data is incomplete.",
      register: "formal",
      position: "The source goes in the gap: 'As X points out, ...'.",
    },
  ],
  practice: [
    {
      type: "multiple-choice",
      prompt: "Which is WRONG?",
      options: [
        "According to the news, it will rain.",
        "According to scientists, the climate is changing.",
        "According to me, the film was great.",
        "According to the report, profits fell.",
      ],
      answer: 2,
      explanation: "Never say 'according to me' — use 'in my opinion' for your own view.",
    },
    {
      type: "gap-fill",
      prompt: "Some people ___ that social media harms teenagers. (report an arguable opinion, one word)",
      answer: "claim",
      accept: ["say", "argue", "believe"],
      explanation: "'claim/argue/say that' report what others think.",
    },
    {
      type: "gap-fill",
      prompt: "___ to the survey, most users prefer the app. (one word)",
      answer: "according",
      explanation: "'According to' cites a source and is followed by a noun.",
    },
    {
      type: "multiple-choice",
      prompt: "Which best introduces an OPPOSING expert view in an essay?",
      options: ["in my opinion", "critics argue that", "for example", "of course"],
      answer: 1,
      explanation: "'Critics argue that' presents a critical/opposing view.",
    },
  ],
};
