import type { ConnectorGroup } from "../types";

export const cause: ConnectorGroup = {
  id: "cause",
  description: "Use these to explain the reason or cause behind something — to answer 'why?'.",
  azDescription: "Bir şeyin səbəbini izah edəndə işlədilir — 'niyə?' sualına cavab.",
  connectors: [
    {
      phrase: "because",
      level: "B1",
      meaning: "for the reason that",
      example: "We stayed at home because it was snowing.",
      register: "neutral",
      position: "Followed by a full clause (subject + verb).",
      pitfall: "'because' ardınca cümlə; 'because of' ardınca isim gəlir.",
      azNote: "Ən sadə səbəb bağlayıcısı — ardınca cümlə.",
    },
    {
      phrase: "because of",
      level: "B1",
      meaning: "as a result of (something)",
      example: "The flight was delayed because of the storm.",
      register: "neutral",
      position: "Followed by a noun or -ing form.",
      synonyms: ["due to", "owing to"],
      pitfall: "Ardınca isim gəlir: 'because of the rain', NOT 'because of it rained'.",
      azNote: "Ardınca isim/-ing — cümlə YOX.",
    },
    {
      phrase: "since",
      level: "B2",
      meaning: "because (when the reason is already known)",
      example: "Since you're here, let's start the meeting.",
      register: "neutral",
      position: "Starts a clause (often at the sentence start).",
      synonyms: ["as", "because"],
      pitfall: "'since' həm 'çünki', həm də 'o vaxtdan bəri' deməkdir — kontekstə bax.",
      azNote: "Səbəb artıq bəlli olanda 'because' əvəzinə.",
    },
    {
      phrase: "as",
      level: "B2",
      meaning: "because (slightly more formal, reason often less emphasised)",
      example: "As it was getting dark, we headed home.",
      register: "formal",
      position: "Starts a clause.",
      synonyms: ["since", "because"],
      azNote: "Yumşaq səbəb — 'madam ki / belə ki'.",
    },
    {
      phrase: "due to",
      level: "B2",
      meaning: "caused by; because of",
      example: "The match was cancelled due to bad weather.",
      register: "formal",
      position: "Followed by a noun (or 'the fact that' + clause).",
      synonyms: ["owing to", "because of"],
      pitfall: "Ənənəvi qaydada 'due to' isimdən sonra (be + due to) işlənir.",
      azNote: "Rəsmi 'səbəbiylə' — ardınca isim.",
    },
    {
      phrase: "owing to",
      level: "C1",
      meaning: "because of (formal)",
      example: "Owing to a lack of funding, the project was postponed.",
      register: "academic",
      position: "Sentence start or mid-sentence; followed by a noun.",
      synonyms: ["due to", "because of"],
      azNote: "Çox rəsmi — adətən yazıda.",
    },
    {
      phrase: "the reason for ... is",
      level: "C1",
      meaning: "used to state a cause explicitly",
      example: "The reason for the delay is a shortage of staff.",
      register: "formal",
      position: "Introduces the cause as a noun phrase.",
      pitfall: "'The reason is BECAUSE' təkrardır — 'The reason is THAT...' işlət.",
      azNote: "Səbəbi açıq şəkildə adlandırmaq üçün.",
    },
  ],
  practice: [
    {
      type: "multiple-choice",
      prompt: "Which is followed by a NOUN?",
      options: ["because", "since", "as", "because of"],
      answer: 3,
      explanation: "'because of the rain' (noun). The others take a clause.",
    },
    {
      type: "gap-fill",
      prompt: "The roads were closed ___ of the heavy snow. (one word)",
      answer: "because",
      explanation: "'because of' + noun expresses cause.",
    },
    {
      type: "multiple-choice",
      prompt: "Choose the correct sentence:",
      options: [
        "We left early because of it was late.",
        "We left early because it was late.",
        "We left early due to it was late.",
        "We left early owing to it was late.",
      ],
      answer: 1,
      explanation: "'because' + clause; 'because of/due to/owing to' need a noun.",
    },
    {
      type: "gap-fill",
      prompt: "___ you already know the topic, we'll skip the introduction. (reason already known, one word)",
      answer: "since",
      accept: ["as"],
      explanation: "'Since/As' introduces a reason that is already known.",
    },
    {
      type: "multiple-choice",
      prompt: "Which is the most FORMAL?",
      options: ["because", "owing to", "since", "as"],
      answer: 1,
      explanation: "'Owing to' is the most formal/academic option.",
    },
  ],
};
