import type { ConnectorGroup } from "../types";

export const clarification: ConnectorGroup = {
  id: "clarification",
  description: "Use these to rephrase, explain, or make an idea clearer in different words.",
  azDescription: "Fikri başqa sözlərlə yenidən izah edib aydınlaşdırmaq üçün işlədilir.",
  connectors: [
    {
      phrase: "in other words",
      level: "B2",
      meaning: "used to explain something more simply or clearly",
      example: "The project is over budget. In other words, we have no money left.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["that is to say", "to put it simply"],
      azNote: "Eyni fikri sadə dillə təkrarlamaq — 'başqa sözlə'.",
    },
    {
      phrase: "that is (to say)",
      level: "C1",
      meaning: "used to add a more precise explanation",
      example: "It happens twice a year, that is, every six months.",
      register: "formal",
      position: "Mid-sentence, between commas.",
      synonyms: ["i.e.", "namely"],
      azNote: "Daqiq izah əlavə edir — 'yəni'. Yazıda 'i.e.'.",
    },
    {
      phrase: "to put it simply",
      level: "B2",
      meaning: "used before a simpler explanation",
      example: "To put it simply, the plan won't work.",
      register: "informal",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in other words", "put simply"],
      azNote: "'Sadəcə desək'.",
    },
    {
      phrase: "I mean",
      level: "B1",
      meaning: "used in speech to explain or correct what you just said",
      example: "Let's meet on Friday. I mean Thursday — Friday is busy.",
      register: "informal",
      position: "Mid-sentence in spoken English.",
      azNote: "Danışıqda izah/düzəliş — 'yəni / demək istəyirəm'.",
    },
    {
      phrase: "in fact",
      level: "B2",
      meaning: "used to add precise or surprising detail to a statement",
      example: "It's a good idea. In fact, it's the best one I've heard.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["actually", "as a matter of fact"],
      azNote: "Dəqiqləşdirmə/gözlənilməz detal — 'əslində / hətta'.",
    },
    {
      phrase: "more precisely",
      level: "C1",
      meaning: "used to give a more exact version of what you said",
      example: "It took a long time — more precisely, almost three hours.",
      register: "formal",
      position: "Sentence start or mid-sentence, with a comma.",
      synonyms: ["to be (more) precise", "specifically"],
      azNote: "Daha dəqiq versiya — 'daha dəqiq desək'.",
    },
  ],
  practice: [
    {
      type: "gap-fill",
      prompt: "We're out of stock. In other ___, you'll have to wait. (one word)",
      answer: "words",
      explanation: "The phrase is 'in other words'.",
    },
    {
      type: "multiple-choice",
      prompt: "Which is used mainly in SPEECH to correct yourself?",
      options: ["that is to say", "I mean", "more precisely", "in other words"],
      answer: 1,
      explanation: "'I mean' is spoken and often corrects what you just said.",
    },
    {
      type: "gap-fill",
      prompt: "It's quite cheap. In ___, it's the cheapest option here. (adds surprising detail, one word)",
      answer: "fact",
      explanation: "'In fact' adds a precise or surprising detail.",
    },
    {
      type: "multiple-choice",
      prompt: "Which written abbreviation means 'that is'?",
      options: ["e.g.", "etc.", "i.e.", "et al."],
      answer: 2,
      explanation: "'i.e.' = that is (to say); 'e.g.' = for example.",
    },
  ],
};
