import type { ConnectorGroup } from "../types";

export const clarification: ConnectorGroup = {
  id: "clarification",
  description: "Use these to rephrase, explain, or make an idea clearer in different words.",
  azDescription: "Fikri başqa sözlərlə yenidən izah edib aydınlaşdırmaq üçün işlədilir.",
  connectors: [
    {
      phrase: "in other words",
      level: "B2",
      meaning: "used to explain something more simply or clearly",
      azMeaning: "başqa sözlə",
      example: "The project is over budget. In other words, we have no money left.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["that is to say", "to put it simply"],
    },
    {
      phrase: "that is (to say)",
      level: "C1",
      meaning: "used to add a more precise explanation",
      azMeaning: "yəni",
      example: "It happens twice a year, that is, every six months.",
      register: "formal",
      position: "Mid-sentence, between commas.",
      synonyms: ["i.e.", "namely"],
      azNote: "Yazıda 'i.e.' kimi qısaldılır.",
    },
    {
      phrase: "to put it simply",
      level: "B2",
      meaning: "used before a simpler explanation",
      azMeaning: "sadə dillə desək",
      example: "To put it simply, the plan won't work.",
      register: "informal",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in other words", "put simply"],
    },
    {
      phrase: "I mean",
      level: "B1",
      meaning: "used in speech to explain or correct what you just said",
      azMeaning: "yəni, demək istəyirəm ki",
      example: "Let's meet on Friday. I mean Thursday — Friday is busy.",
      register: "informal",
      position: "Mid-sentence in spoken English.",
      azNote: "Danışıqda izah/düzəliş üçün.",
    },
    {
      phrase: "in fact",
      level: "B2",
      meaning: "used to add precise or surprising detail to a statement",
      azMeaning: "əslində, hətta",
      example: "It's a good idea. In fact, it's the best one I've heard.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["actually", "as a matter of fact"],
    },
    {
      phrase: "more precisely",
      level: "C1",
      meaning: "used to give a more exact version of what you said",
      azMeaning: "daha dəqiq desək",
      example: "It took a long time — more precisely, almost three hours.",
      register: "formal",
      position: "Sentence start or mid-sentence, with a comma.",
      synonyms: ["to be (more) precise", "specifically"],
    },
    {
      phrase: "this means that",
      level: "B2",
      meaning: "used to explain the result or sense of something",
      azMeaning: "bu o deməkdir ki",
      example: "The shop is closed. This means that we must wait.",
      register: "neutral",
      position: "Sentence start, before a clause.",
    },
    {
      phrase: "to put it another way",
      level: "B2",
      meaning: "used to explain the same idea differently",
      azMeaning: "başqa cür desək",
      example: "It's not profitable. To put it another way, we're losing money.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in other words", "put differently"],
    },
    {
      phrase: "or rather",
      level: "B2",
      meaning: "used to correct or make what you said more exact",
      azMeaning: "daha doğrusu",
      example: "He's a friend, or rather, an old colleague.",
      register: "neutral",
      position: "Mid-sentence, between commas.",
    },
    {
      phrase: "in essence",
      level: "C1",
      meaning: "in the most basic and important way",
      azMeaning: "mahiyyət etibarilə, əslində",
      example: "In essence, the two plans are the same.",
      register: "formal",
      position: "Sentence start, followed by a comma.",
    },
    {
      phrase: "strictly speaking",
      level: "C1",
      meaning: "if you use the exact meaning of the words",
      azMeaning: "dəqiq desək, əslində",
      example: "Strictly speaking, a tomato is a fruit.",
      register: "formal",
      position: "Sentence start, followed by a comma.",
    },
    {
      phrase: "to be precise",
      level: "C1",
      meaning: "used to give the exact detail",
      azMeaning: "dəqiq desək",
      example: "It happened in 2010 — in May, to be precise.",
      register: "neutral",
      position: "Mid-sentence or end, with commas.",
    },
    {
      phrase: "as a matter of fact",
      level: "C1",
      meaning: "in reality (often adds a surprising detail)",
      azMeaning: "əslində, doğrusu",
      example: "I know him well. As a matter of fact, we grew up together.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in fact", "actually"],
    },
  ],
  practice: [
    {
      type: "gap-fill",
      prompt: "We're out of stock. In other ___, you'll have to wait. (one word)",
      answer: "words",
      explanation: "The phrase is 'in other words'.",
    },
    {
      type: "multiple-choice",
      prompt: "Which is used mainly in SPEECH to correct yourself?",
      options: ["that is to say", "I mean", "more precisely", "in other words"],
      answer: 1,
      explanation: "'I mean' is spoken and often corrects what you just said.",
    },
    {
      type: "gap-fill",
      prompt: "It's quite cheap. In ___, it's the cheapest option here. (adds surprising detail, one word)",
      answer: "fact",
      explanation: "'In fact' adds a precise or surprising detail.",
    },
    {
      type: "multiple-choice",
      prompt: "Which written abbreviation means 'that is'?",
      options: ["e.g.", "etc.", "i.e.", "et al."],
      answer: 2,
      explanation: "'i.e.' = that is (to say); 'e.g.' = for example.",
    },
  ],
};
