import type { ConnectorGroup } from "../types";

export const comparison: ConnectorGroup = {
  id: "comparison",
  description: "Use these to show that two things are similar or that the same idea applies again.",
  azDescription: "İki şeyin oxşar olduğunu və ya eyni fikrin təkrar keçərli olduğunu göstərəndə.",
  connectors: [
    {
      phrase: "like",
      level: "B1",
      meaning: "similar to; in the same way as",
      example: "Like her sister, she loves painting.",
      register: "neutral",
      position: "Before a noun.",
      pitfall: "Müqayisədə cümlə gələrsə 'as' işlət: 'as I said', NOT 'like I said' (rəsmi).",
      azNote: "İsimdən əvvəl müqayisə — 'kimi'.",
    },
    {
      phrase: "similarly",
      level: "B2",
      meaning: "in a similar way",
      example: "Dogs need daily exercise. Similarly, cats need regular play.",
      register: "formal",
      position: "Sentence start, followed by a comma.",
      synonyms: ["likewise", "in the same way"],
      azNote: "İki vəziyyəti oxşar kimi bağlayır — 'eynilə / oxşar şəkildə'.",
    },
    {
      phrase: "likewise",
      level: "C1",
      meaning: "in the same way; also",
      example: "The first plan failed. Likewise, the second one collapsed.",
      register: "formal",
      position: "Sentence start, followed by a comma.",
      synonyms: ["similarly", "in the same way"],
      azNote: "Rəsmi 'eyni şəkildə'.",
    },
    {
      phrase: "in the same way",
      level: "B2",
      meaning: "used to compare two similar situations",
      example: "Plants need light to grow. In the same way, children need encouragement.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["similarly", "likewise"],
      azNote: "Açıq müqayisə — 'eyni şəkildə'.",
    },
    {
      phrase: "just as ... so",
      level: "C1",
      meaning: "used to draw a strong parallel between two things",
      example: "Just as exercise strengthens the body, so reading strengthens the mind.",
      register: "academic",
      position: "Connects two parallel clauses.",
      azNote: "Güclü paralel qurur — 'necə ki ..., eləcə də ...'.",
    },
    {
      phrase: "compared to / with",
      level: "B2",
      meaning: "in relation to (used when measuring difference or similarity)",
      example: "Compared to last year, sales have doubled.",
      register: "neutral",
      position: "Sentence start (comma after) or mid-sentence; followed by a noun.",
      synonyms: ["in comparison with"],
      azNote: "İki şeyi ölçərkən müqayisə — ardınca isim.",
    },
  ],
  practice: [
    {
      type: "gap-fill",
      prompt: "Cats are independent. ___, many dogs prefer company. (in a similar way, one word)",
      answer: "similarly",
      accept: ["likewise"],
      explanation: "'Similarly/Likewise' links two similar situations.",
    },
    {
      type: "multiple-choice",
      prompt: "Which is the most FORMAL word for 'in the same way'?",
      options: ["like", "likewise", "and", "too"],
      answer: 1,
      explanation: "'Likewise' is the formal comparison connector.",
    },
    {
      type: "gap-fill",
      prompt: "___ to last month, the results have improved. (two-step: word + 'to') Write the first word.",
      answer: "compared",
      explanation: "'Compared to/with' introduces a comparison.",
    },
    {
      type: "multiple-choice",
      prompt: "Choose the correct sentence:",
      options: [
        "Just as plants need water, so people need rest.",
        "Just as plants need water, but people need rest.",
        "Just like plants need water, so people rest.",
        "Just as plants need water people need rest.",
      ],
      answer: 0,
      explanation: "The parallel structure is 'Just as ..., so ...'.",
    },
  ],
};
