import type { ConnectorGroup } from "../types";

export const conclusion: ConnectorGroup = {
  id: "conclusion",
  description: "Use these to summarise your points or signal that you are finishing.",
  azDescription: "Fikirlərini yekunlaşdırıb nəticəyə gələndə işlədilir.",
  connectors: [
    {
      phrase: "in conclusion",
      level: "B2",
      meaning: "used to introduce the final summary",
      example: "In conclusion, regular exercise improves both body and mind.",
      register: "formal",
      position: "Sentence start, followed by a comma.",
      synonyms: ["to conclude", "to sum up"],
      pitfall: "Esse yazısında yalnız BİR dəfə, son abzasda işlət.",
      azNote: "Esse/yazının sonunda yekun — 'nəticədə'.",
    },
    {
      phrase: "to sum up",
      level: "B2",
      meaning: "used to give a short summary of the main points",
      example: "To sum up, the new system is faster but more expensive.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in summary", "to summarise"],
      azNote: "Əsas məqamları qısaca toplamaq — 'xülasə'.",
    },
    {
      phrase: "overall",
      level: "B2",
      meaning: "considering everything; in general",
      example: "Overall, it was a successful year for the company.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["all in all", "on the whole"],
      azNote: "Ümumi qiymət — 'ümumilikdə'.",
    },
    {
      phrase: "all in all",
      level: "B2",
      meaning: "when everything is considered",
      example: "All in all, the trip was worth the money.",
      register: "informal",
      position: "Sentence start, followed by a comma.",
      synonyms: ["overall", "on the whole"],
      azNote: "Qeyri-rəsmi yekun — 'hər şeyi nəzərə alsaq'.",
    },
    {
      phrase: "in short",
      level: "B2",
      meaning: "used to give the main point in a few words",
      example: "In short, the plan is too risky.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in brief", "put simply"],
      azNote: "Qısaca — 'sözün qısası'.",
    },
    {
      phrase: "to conclude",
      level: "C1",
      meaning: "used to introduce final remarks (formal)",
      example: "To conclude, the evidence strongly supports the new policy.",
      register: "academic",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in conclusion", "finally"],
      azNote: "Rəsmi/akademik bağlanış.",
    },
  ],
  practice: [
    {
      type: "gap-fill",
      prompt: "In ___, the benefits clearly outweigh the costs. (final summary, one word)",
      answer: "conclusion",
      explanation: "'In conclusion' opens the final summary.",
    },
    {
      type: "multiple-choice",
      prompt: "Which is the most INFORMAL?",
      options: ["in conclusion", "all in all", "to conclude", "in summary"],
      answer: 1,
      explanation: "'all in all' is informal; the others suit formal writing.",
    },
    {
      type: "gap-fill",
      prompt: "To ___ up, we recommend option B. (one word)",
      answer: "sum",
      explanation: "The phrase is 'to sum up'.",
    },
    {
      type: "multiple-choice",
      prompt: "How many times should you use 'In conclusion' in one essay?",
      options: ["Once, at the end", "In every paragraph", "At the start and end", "Never"],
      answer: 0,
      explanation: "Use a conclusion signal once, in the final paragraph.",
    },
  ],
};
