import type { ConnectorGroup } from "../types";

export const conclusion: ConnectorGroup = {
  id: "conclusion",
  description: "Use these to summarise your points or signal that you are finishing.",
  azDescription: "Fikirlərini yekunlaşdırıb nəticəyə gələndə işlədilir.",
  connectors: [
    {
      phrase: "in conclusion",
      level: "B2",
      meaning: "used to introduce the final summary",
      azMeaning: "nəticədə, yekun olaraq",
      example: "In conclusion, regular exercise improves both body and mind.",
      register: "formal",
      position: "Sentence start, followed by a comma.",
      synonyms: ["to conclude", "to sum up"],
      pitfall: "Esse yazısında yalnız BİR dəfə, son abzasda işlət.",
    },
    {
      phrase: "to sum up",
      level: "B2",
      meaning: "used to give a short summary of the main points",
      azMeaning: "xülasə, ümumiləşdirsək",
      example: "To sum up, the new system is faster but more expensive.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in summary", "to summarise"],
    },
    {
      phrase: "overall",
      level: "B2",
      meaning: "considering everything; in general",
      azMeaning: "ümumilikdə",
      example: "Overall, it was a successful year for the company.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["all in all", "on the whole"],
    },
    {
      phrase: "all in all",
      level: "B2",
      meaning: "when everything is considered",
      azMeaning: "hər şeyi nəzərə alsaq",
      example: "All in all, the trip was worth the money.",
      register: "informal",
      position: "Sentence start, followed by a comma.",
      synonyms: ["overall", "on the whole"],
    },
    {
      phrase: "in short",
      level: "B2",
      meaning: "used to give the main point in a few words",
      azMeaning: "qısaca, sözün qısası",
      example: "In short, the plan is too risky.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in brief", "put simply"],
    },
    {
      phrase: "to conclude",
      level: "C1",
      meaning: "used to introduce final remarks (formal)",
      azMeaning: "yekunlaşdırsaq, son olaraq",
      example: "To conclude, the evidence strongly supports the new policy.",
      register: "academic",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in conclusion", "finally"],
      azNote: "Rəsmi/akademik bağlanış.",
    },
    {
      phrase: "in summary",
      level: "B2",
      meaning: "used to give the main points briefly",
      azMeaning: "xülasə olaraq",
      example: "In summary, the project met all its goals.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["to sum up", "to summarise"],
    },
    {
      phrase: "on the whole",
      level: "B2",
      meaning: "considering everything; in general",
      azMeaning: "ümumilikdə, əsasən",
      example: "On the whole, the plan was a success.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["overall", "by and large"],
    },
    {
      phrase: "all things considered",
      level: "C1",
      meaning: "after thinking about everything",
      azMeaning: "hər şeyi nəzərə alsaq",
      example: "All things considered, it was a good decision.",
      register: "formal",
      position: "Sentence start, followed by a comma.",
    },
    {
      phrase: "by and large",
      level: "C1",
      meaning: "generally; mostly",
      azMeaning: "ümumiyyətlə, əsasən",
      example: "By and large, customers were satisfied with the service.",
      register: "formal",
      position: "Sentence start, followed by a comma.",
    },
    {
      phrase: "ultimately",
      level: "C1",
      meaning: "in the end; most importantly",
      azMeaning: "son nəticədə, axırda",
      example: "Ultimately, the choice is yours.",
      register: "neutral",
      position: "Sentence start or mid-sentence.",
    },
    {
      phrase: "to summarise",
      level: "B2",
      meaning: "used to give a short version of the main points",
      azMeaning: "ümumiləşdirsək",
      example: "To summarise, we need more time and money.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
    },
    {
      phrase: "on balance",
      level: "C1",
      meaning: "after considering all sides",
      azMeaning: "ümumilikdə, tərəzidə çəkəndə",
      example: "On balance, the benefits outweigh the costs.",
      register: "formal",
      position: "Sentence start, followed by a comma.",
    },
  ],
  practice: [
    {
      type: "gap-fill",
      prompt: "In ___, the benefits clearly outweigh the costs. (final summary, one word)",
      answer: "conclusion",
      explanation: "'In conclusion' opens the final summary.",
    },
    {
      type: "multiple-choice",
      prompt: "Which is the most INFORMAL?",
      options: ["in conclusion", "all in all", "to conclude", "in summary"],
      answer: 1,
      explanation: "'all in all' is informal; the others suit formal writing.",
    },
    {
      type: "gap-fill",
      prompt: "To ___ up, we recommend option B. (one word)",
      answer: "sum",
      explanation: "The phrase is 'to sum up'.",
    },
    {
      type: "multiple-choice",
      prompt: "How many times should you use 'In conclusion' in one essay?",
      options: ["Once, at the end", "In every paragraph", "At the start and end", "Never"],
      answer: 0,
      explanation: "Use a conclusion signal once, in the final paragraph.",
    },
  ],
};
