import type { ConnectorGroup } from "../types";

export const condition: ConnectorGroup = {
  id: "condition",
  description: "Use these to say that one thing depends on another — 'only if this, then that'.",
  azDescription: "Bir şeyin başqa bir şərtə bağlı olduğunu bildirəndə işlədilir.",
  connectors: [
    {
      phrase: "if",
      level: "B1",
      meaning: "on condition that",
      example: "If it rains, we will stay at home.",
      register: "neutral",
      position: "Starts a clause; a comma separates the two clauses.",
      pitfall: "Şərt cümləsində 'will' işlətmə: 'If it RAINS', NOT 'If it will rain'.",
      azNote: "Ən sadə şərt — 'əgər'.",
    },
    {
      phrase: "unless",
      level: "B2",
      meaning: "except if; if not",
      example: "We'll go for a walk unless it rains.",
      register: "neutral",
      position: "Starts a clause.",
      pitfall: "'unless' artıq inkardır — 'unless you don't...' demə.",
      azNote: "'əgər ...-masa' (= if not).",
    },
    {
      phrase: "as long as",
      level: "B2",
      meaning: "only if; on condition that",
      example: "You can stay as long as you keep quiet.",
      register: "neutral",
      position: "Starts or joins a clause.",
      synonyms: ["so long as", "provided that"],
      azNote: "'bir şərtlə ki / o qədər ki'.",
    },
    {
      phrase: "provided (that)",
      level: "C1",
      meaning: "only if a particular thing happens (formal)",
      example: "The deal will go ahead provided that both sides agree.",
      register: "formal",
      position: "Joins a clause; 'that' is optional.",
      synonyms: ["providing that", "on condition that"],
      azNote: "Rəsmi şərt — 'bu şərtlə ki'.",
    },
    {
      phrase: "in case",
      level: "B2",
      meaning: "because something might happen (a precaution)",
      example: "Take an umbrella in case it rains.",
      register: "neutral",
      position: "Joins a clause.",
      pitfall: "'in case' ≠ 'if'. 'Take it in case it rains' = ehtiyat üçün, əvvəlcədən.",
      azNote: "Ehtiyat tədbiri — 'birdən ... olar deyə'.",
    },
    {
      phrase: "otherwise",
      level: "B2",
      meaning: "if not; or else",
      example: "Hurry up, otherwise we'll miss the train.",
      register: "neutral",
      position: "Sentence start (comma after) or after a comma.",
      synonyms: ["or else", "if not"],
      azNote: "'əks halda / yoxsa'.",
    },
  ],
  practice: [
    {
      type: "multiple-choice",
      prompt: "Choose the correct sentence:",
      options: [
        "If it will rain, we'll stay home.",
        "If it rains, we'll stay home.",
        "If it rain, we'll stay home.",
        "If it would rain, we'll stay home.",
      ],
      answer: 1,
      explanation: "In a first conditional, use the present simple after 'if'.",
    },
    {
      type: "gap-fill",
      prompt: "We'll be late ___ we leave now. (= if we don't; one word)",
      answer: "unless",
      explanation: "'unless' = 'if not'.",
    },
    {
      type: "gap-fill",
      prompt: "Take some cash ___ case the card doesn't work. (one word)",
      answer: "in",
      explanation: "'in case' expresses a precaution.",
    },
    {
      type: "multiple-choice",
      prompt: "Which means 'or else'?",
      options: ["as long as", "provided that", "otherwise", "unless"],
      answer: 2,
      explanation: "'Otherwise' = if not / or else.",
    },
    {
      type: "multiple-choice",
      prompt: "Which sentence is correct?",
      options: [
        "Unless you don't hurry, we'll be late.",
        "Unless you hurry, we'll be late.",
        "Unless you will hurry, we'll be late.",
        "Unless you hurried, we'll be late.",
      ],
      answer: 1,
      explanation: "'Unless' is already negative — don't add 'don't'.",
    },
  ],
};
