import type { ConnectorGroup } from "../types";

export const condition: ConnectorGroup = {
  id: "condition",
  description: "Use these to say that one thing depends on another — 'only if this, then that'.",
  azDescription: "Bir şeyin başqa bir şərtə bağlı olduğunu bildirəndə işlədilir.",
  connectors: [
    {
      phrase: "if",
      level: "B1",
      meaning: "on condition that",
      azMeaning: "əgər",
      example: "If it rains, we will stay at home.",
      register: "neutral",
      position: "Starts a clause; a comma separates the two clauses.",
      pitfall: "Şərt cümləsində 'will' işlətmə: 'If it RAINS', NOT 'If it will rain'.",
    },
    {
      phrase: "unless",
      level: "B2",
      meaning: "except if; if not",
      azMeaning: "əgər ...-masa, ...-madıqca",
      example: "We'll go for a walk unless it rains.",
      register: "neutral",
      position: "Starts a clause.",
      pitfall: "'unless' artıq inkardır — 'unless you don't...' demə.",
    },
    {
      phrase: "as long as",
      level: "B2",
      meaning: "only if; on condition that",
      azMeaning: "bir şərtlə ki, o qədər ki",
      example: "You can stay as long as you keep quiet.",
      register: "neutral",
      position: "Starts or joins a clause.",
      synonyms: ["so long as", "provided that"],
    },
    {
      phrase: "provided (that)",
      level: "C1",
      meaning: "only if a particular thing happens (formal)",
      azMeaning: "bu şərtlə ki",
      example: "The deal will go ahead provided that both sides agree.",
      register: "formal",
      position: "Joins a clause; 'that' is optional.",
      synonyms: ["providing that", "on condition that"],
      azNote: "Rəsmi şərt bildirir.",
    },
    {
      phrase: "in case",
      level: "B2",
      meaning: "because something might happen (a precaution)",
      azMeaning: "birdən ... olar deyə, ehtiyat üçün",
      example: "Take an umbrella in case it rains.",
      register: "neutral",
      position: "Joins a clause.",
      pitfall: "'in case' ≠ 'if'. 'Take it in case it rains' = ehtiyat üçün, əvvəlcədən.",
    },
    {
      phrase: "otherwise",
      level: "B2",
      meaning: "if not; or else",
      azMeaning: "əks halda, yoxsa",
      example: "Hurry up, otherwise we'll miss the train.",
      register: "neutral",
      position: "Sentence start (comma after) or after a comma.",
      synonyms: ["or else", "if not"],
    },
    {
      phrase: "even if",
      level: "B2",
      meaning: "whether or not something happens",
      azMeaning: "hətta ...-sa belə",
      example: "Even if it rains, we will go.",
      register: "neutral",
      position: "Starts a clause.",
      pitfall: "'even if' (fərziyyə) ≠ 'even though' (real fakt).",
    },
    {
      phrase: "only if",
      level: "B2",
      meaning: "on the single condition that",
      azMeaning: "yalnız ...-sa",
      example: "I'll help only if you ask politely.",
      register: "neutral",
      position: "Joins or starts a clause.",
    },
    {
      phrase: "supposing (that)",
      level: "B2",
      meaning: "what if; imagine that",
      azMeaning: "tutaq ki, fərz et ki",
      example: "Supposing that it fails, what's our plan?",
      register: "informal",
      position: "Starts a clause; 'that' is optional.",
      synonyms: ["suppose", "what if"],
    },
    {
      phrase: "assuming (that)",
      level: "C1",
      meaning: "if we accept that something is true",
      azMeaning: "fərz etsək ki",
      example: "Assuming that the data is correct, the results are valid.",
      register: "neutral",
      position: "Starts a clause; 'that' is optional.",
    },
    {
      phrase: "on condition that",
      level: "C1",
      meaning: "only if a particular thing is agreed",
      azMeaning: "bu şərtlə ki",
      example: "He agreed on condition that his name stayed secret.",
      register: "formal",
      position: "Joins a clause.",
      synonyms: ["provided that", "as long as"],
    },
    {
      phrase: "in the event of",
      level: "C1",
      meaning: "if something happens",
      azMeaning: "...halında, baş verərsə",
      example: "In the event of a fire, use the stairs.",
      register: "formal",
      position: "Followed by a noun.",
      pitfall: "Ardınca isim: 'in the event of'; cümlə üçün 'in the event that'.",
    },
    {
      phrase: "whether or not",
      level: "B2",
      meaning: "regardless of whether something is true",
      azMeaning: "...-ıb-olmamasından asılı olmayaraq",
      example: "We'll go whether or not it rains.",
      register: "neutral",
      position: "Joins a clause.",
    },
  ],
  practice: [
    {
      type: "multiple-choice",
      prompt: "Choose the correct sentence:",
      options: [
        "If it will rain, we'll stay home.",
        "If it rains, we'll stay home.",
        "If it rain, we'll stay home.",
        "If it would rain, we'll stay home.",
      ],
      answer: 1,
      explanation: "In a first conditional, use the present simple after 'if'.",
    },
    {
      type: "gap-fill",
      prompt: "We'll be late ___ we leave now. (= if we don't; one word)",
      answer: "unless",
      explanation: "'unless' = 'if not'.",
    },
    {
      type: "gap-fill",
      prompt: "Take some cash ___ case the card doesn't work. (one word)",
      answer: "in",
      explanation: "'in case' expresses a precaution.",
    },
    {
      type: "multiple-choice",
      prompt: "Which means 'or else'?",
      options: ["as long as", "provided that", "otherwise", "unless"],
      answer: 2,
      explanation: "'Otherwise' = if not / or else.",
    },
    {
      type: "multiple-choice",
      prompt: "Which sentence is correct?",
      options: [
        "Unless you don't hurry, we'll be late.",
        "Unless you hurry, we'll be late.",
        "Unless you will hurry, we'll be late.",
        "Unless you hurried, we'll be late.",
      ],
      answer: 1,
      explanation: "'Unless' is already negative — don't add 'don't'.",
    },
  ],
};
