import type { ConnectorGroup } from "../types";

export const contrast: ConnectorGroup = {
  id: "contrast",
  description: "Use these to show a difference, a surprise, or an opposite idea to what came before.",
  azDescription: "Əvvəlki fikrə zidd və ya gözlənilməz bir fikir bildirəndə işlədilir.",
  connectors: [
    {
      phrase: "but",
      level: "B1",
      meaning: "used to introduce a contrasting idea",
      azMeaning: "amma, lakin",
      example: "I wanted to go out, but it was raining.",
      register: "neutral",
      position: "Joins two clauses in the middle of a sentence.",
      pitfall: "Rəsmi yazıda cümləyə 'But' ilə başlamaqdan çəkin — 'However' işlət.",
    },
    {
      phrase: "however",
      level: "B2",
      meaning: "but; in spite of that",
      azMeaning: "lakin, buna baxmayaraq",
      example: "The plan looked perfect. However, it failed completely.",
      register: "formal",
      position: "Sentence start, followed by a comma.",
      synonyms: ["nevertheless", "nonetheless"],
      pitfall: "İki cümləni birləşdirmək üçün nöqtə/nöqtəli vergül lazımdır: '...failed. However, ...'",
    },
    {
      phrase: "although",
      level: "B2",
      meaning: "in spite of the fact that",
      azMeaning: "baxmayaraq ki, hərçənd",
      example: "Although it was raining, we went for a walk.",
      register: "neutral",
      position: "Starts a clause; a comma separates the two clauses.",
      synonyms: ["even though", "though"],
      pitfall: "'Although ... but ...' YANLIŞdır — birini seç: 'Although it rained, we walked.'",
    },
    {
      phrase: "even though",
      level: "B2",
      meaning: "despite the fact that (stronger than 'although')",
      azMeaning: "baxmayaraq ki (daha güclü)",
      example: "Even though he was tired, he finished the race.",
      register: "neutral",
      position: "Starts a clause.",
      synonyms: ["although", "though"],
      azNote: "'although'-dan daha vurğulu vurğu verir.",
    },
    {
      phrase: "despite",
      level: "B2",
      meaning: "without being affected by; in spite of",
      azMeaning: "-ə baxmayaraq",
      example: "Despite the rain, the match continued.",
      register: "formal",
      position: "Followed by a noun or -ing form (NOT a full clause).",
      synonyms: ["in spite of"],
      pitfall: "'Despite OF' YANLIŞ. Cümlə gələrsə: 'despite the fact that...'",
    },
    {
      phrase: "on the other hand",
      level: "B2",
      meaning: "used to present the opposite side of an argument",
      azMeaning: "digər tərəfdən",
      example: "City life is exciting. On the other hand, it can be stressful.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in contrast", "conversely"],
      azNote: "İki tərəfi (üstünlük/çatışmazlıq) müqayisə edəndə.",
    },
    {
      phrase: "nevertheless",
      level: "C1",
      meaning: "in spite of that; even so",
      azMeaning: "buna baxmayaraq, yenə də",
      example: "The evidence was weak. Nevertheless, the theory became popular.",
      register: "academic",
      position: "Sentence start, followed by a comma.",
      synonyms: ["nonetheless", "however"],
      azNote: "Rəsmi/akademik üslub.",
    },
    {
      phrase: "whereas",
      level: "C1",
      meaning: "used to compare two different facts",
      azMeaning: "halbuki, isə",
      example: "Some people love spicy food, whereas others can't stand it.",
      register: "formal",
      position: "Joins two contrasting clauses (often after a comma).",
      synonyms: ["while"],
      azNote: "İki faktı yan-yana müqayisə edir.",
    },
    {
      phrase: "yet",
      level: "B2",
      meaning: "but; despite that",
      azMeaning: "amma, buna baxmayaraq",
      example: "The task was simple, yet he failed it.",
      register: "neutral",
      position: "Joins clauses (after a comma) or sentence-initial.",
      synonyms: ["but", "still"],
    },
    {
      phrase: "still",
      level: "B2",
      meaning: "despite that; nevertheless",
      azMeaning: "yenə də",
      example: "It's expensive. Still, it's worth the money.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
    },
    {
      phrase: "though",
      level: "B2",
      meaning: "however (often at the end of a sentence)",
      azMeaning: "amma, hərçənd",
      example: "It's a long film. It's very good, though.",
      register: "informal",
      position: "Starts a clause, or at the END of a sentence (informal).",
      synonyms: ["although", "however"],
      pitfall: "Cümlə sonunda 'though' = 'however' (qeyri-rəsmi).",
    },
    {
      phrase: "nonetheless",
      level: "C1",
      meaning: "in spite of that",
      azMeaning: "buna baxmayaraq, yenə də",
      example: "The risks are clear. Nonetheless, they decided to invest.",
      register: "academic",
      position: "Sentence start, followed by a comma.",
      synonyms: ["nevertheless", "however"],
    },
    {
      phrase: "in contrast",
      level: "B2",
      meaning: "used to compare two opposite things",
      azMeaning: "bunun əksinə, müqayisədə",
      example: "Sales rose in the city. In contrast, they fell in rural areas.",
      register: "formal",
      position: "Sentence start, followed by a comma.",
      pitfall: "'In contrast,' (cümlə başı) ≠ 'in contrast TO/WITH' (isim).",
    },
    {
      phrase: "conversely",
      level: "C1",
      meaning: "in an opposite way",
      azMeaning: "əksinə, tərsinə",
      example: "More effort often means better grades; conversely, less work leads to failure.",
      register: "academic",
      position: "Sentence start, followed by a comma.",
    },
    {
      phrase: "while",
      level: "B2",
      meaning: "whereas; although",
      azMeaning: "halbuki, ...-sa da",
      example: "While the idea is good, it is too expensive.",
      register: "neutral",
      position: "Starts a clause.",
      azNote: "İki məna: 'while' = halbuki (ziddiyyət) və 'while' = ikən (zaman).",
    },
    {
      phrase: "in spite of",
      level: "B2",
      meaning: "despite",
      azMeaning: "-ə baxmayaraq",
      example: "In spite of the rain, the festival went ahead.",
      register: "formal",
      position: "Followed by a noun or -ing form.",
      pitfall: "Üç ayrı söz: 'inspite' YANLIŞ. Ardınca isim/-ing.",
    },
    {
      phrase: "albeit",
      level: "C1",
      meaning: "although; even if",
      azMeaning: "hərçənd, ...-sa da",
      example: "It was a useful, albeit expensive, lesson.",
      register: "academic",
      position: "Usually before an adjective, adverb or phrase (not a full clause).",
      pitfall: "Tam cümlə yox, ifadə ilə: 'albeit briefly'.",
    },
  ],
  practice: [
    {
      type: "multiple-choice",
      prompt: "Which is followed by a NOUN, not a full clause?",
      options: ["although", "despite", "even though", "however"],
      answer: 1,
      explanation: "'Despite the rain' (noun). The others take a clause.",
    },
    {
      type: "gap-fill",
      prompt: "___ it was expensive, we decided to buy it. (one word)",
      answer: "although",
      accept: ["though"],
      explanation: "'Although/Though' starts a contrast clause.",
    },
    {
      type: "multiple-choice",
      prompt: "Which sentence is correct?",
      options: [
        "Although it was late, but we kept working.",
        "Although it was late, we kept working.",
        "Despite it was late, we kept working.",
        "However it was late, we kept working.",
      ],
      answer: 1,
      explanation: "Never use 'although ... but ...' together; 'despite' needs a noun.",
    },
    {
      type: "gap-fill",
      prompt: "The first option is cheap. On the other ___, it is slow. (one word)",
      answer: "hand",
      explanation: "The fixed phrase is 'on the other hand'.",
    },
    {
      type: "multiple-choice",
      prompt: "Choose the correct form:",
      options: ["despite of the noise", "despite the noise", "despite to the noise", "despite of noise"],
      answer: 1,
      explanation: "'Despite' is never followed by 'of': 'despite the noise'.",
    },
  ],
};
