import type { ConnectorGroup } from "../types";

export const contrast: ConnectorGroup = {
  id: "contrast",
  description: "Use these to show a difference, a surprise, or an opposite idea to what came before.",
  azDescription: "Əvvəlki fikrə zidd və ya gözlənilməz bir fikir bildirəndə işlədilir.",
  connectors: [
    {
      phrase: "but",
      level: "B1",
      meaning: "used to introduce a contrasting idea",
      example: "I wanted to go out, but it was raining.",
      register: "neutral",
      position: "Joins two clauses in the middle of a sentence.",
      pitfall: "Rəsmi yazıda cümləyə 'But' ilə başlamaqdan çəkin — 'However' işlət.",
      azNote: "Ən sadə ziddiyyət bağlayıcısı — 'amma'.",
    },
    {
      phrase: "however",
      level: "B2",
      meaning: "but; in spite of that",
      example: "The plan looked perfect. However, it failed completely.",
      register: "formal",
      position: "Sentence start, followed by a comma.",
      synonyms: ["nevertheless", "nonetheless"],
      pitfall: "İki cümləni birləşdirmək üçün nöqtə və ya nöqtəli vergül lazımdır: '...failed. However, ...' NOT 'failed, however ...'",
      azNote: "Cümlə başında, sonra vergül — yazının ən çox işlənən ziddiyyət sözü.",
    },
    {
      phrase: "although",
      level: "B2",
      meaning: "in spite of the fact that",
      example: "Although it was raining, we went for a walk.",
      register: "neutral",
      position: "Starts a clause; a comma separates the two clauses.",
      synonyms: ["even though", "though"],
      pitfall: "'Although ... but ...' YANLIŞdır — birini seç: 'Although it rained, we walked.'",
      azNote: "Bir cümlədə iki hissəni birləşdirir (bənd başında).",
    },
    {
      phrase: "even though",
      level: "B2",
      meaning: "despite the fact that (stronger than 'although')",
      example: "Even though he was tired, he finished the race.",
      register: "neutral",
      position: "Starts a clause.",
      synonyms: ["although", "though"],
      azNote: "'although'-dan daha güclü/vurğulu.",
    },
    {
      phrase: "despite",
      level: "B2",
      meaning: "without being affected by; in spite of",
      example: "Despite the rain, the match continued.",
      register: "formal",
      position: "Followed by a noun or -ing form (NOT a full clause).",
      synonyms: ["in spite of"],
      pitfall: "'Despite OF' YANLIŞ. Cümlə gələrsə: 'despite the fact that...'",
      azNote: "Ardınca isim/-ing gəlir, bütöv cümlə YOX.",
    },
    {
      phrase: "on the other hand",
      level: "B2",
      meaning: "used to present the opposite side of an argument",
      example: "City life is exciting. On the other hand, it can be stressful.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in contrast", "conversely"],
      azNote: "İki tərəfi (üstünlük/çatışmazlıq) müqayisə edəndə.",
    },
    {
      phrase: "nevertheless",
      level: "C1",
      meaning: "in spite of that; even so",
      example: "The evidence was weak. Nevertheless, the theory became popular.",
      register: "academic",
      position: "Sentence start, followed by a comma.",
      synonyms: ["nonetheless", "however"],
      azNote: "Rəsmi/akademik 'buna baxmayaraq'.",
    },
    {
      phrase: "whereas",
      level: "C1",
      meaning: "used to compare two different facts",
      example: "Some people love spicy food, whereas others can't stand it.",
      register: "formal",
      position: "Joins two contrasting clauses (often after a comma).",
      synonyms: ["while"],
      azNote: "İki faktı yan-yana müqayisə edir.",
    },
  ],
  practice: [
    {
      type: "multiple-choice",
      prompt: "Which is followed by a NOUN, not a full clause?",
      options: ["although", "despite", "even though", "however"],
      answer: 1,
      explanation: "'Despite the rain' (noun). The others take a clause.",
    },
    {
      type: "gap-fill",
      prompt: "___ it was expensive, we decided to buy it. (one word)",
      answer: "although",
      accept: ["though"],
      explanation: "'Although/Though' starts a contrast clause.",
    },
    {
      type: "multiple-choice",
      prompt: "Which sentence is correct?",
      options: [
        "Although it was late, but we kept working.",
        "Although it was late, we kept working.",
        "Despite it was late, we kept working.",
        "However it was late, we kept working.",
      ],
      answer: 1,
      explanation: "Never use 'although ... but ...' together; 'despite' needs a noun.",
    },
    {
      type: "gap-fill",
      prompt: "The first option is cheap. On the other ___, it is slow. (one word)",
      answer: "hand",
      explanation: "The fixed phrase is 'on the other hand'.",
    },
    {
      type: "multiple-choice",
      prompt: "Choose the correct form:",
      options: ["despite of the noise", "despite the noise", "despite to the noise", "despite of noise"],
      answer: 1,
      explanation: "'Despite' is never followed by 'of': 'despite the noise'.",
    },
  ],
};
