import type { ConnectorGroup } from "../types";

export const emphasis: ConnectorGroup = {
  id: "emphasis",
  description: "Use these to stress a point and show that it is important or certain.",
  azDescription: "Bir fikri vurğulayıb onun vacib və ya əmin olduğunu göstərmək üçün.",
  connectors: [
    {
      phrase: "of course",
      level: "B1",
      meaning: "used to say something is obvious or expected",
      azMeaning: "əlbəttə",
      example: "Of course, you can borrow my car.",
      register: "neutral",
      position: "Sentence start (comma after) or mid-sentence.",
      synonyms: ["naturally", "obviously"],
    },
    {
      phrase: "obviously",
      level: "B2",
      meaning: "in a way that is easy to see or understand",
      azMeaning: "açıq-aşkar, aydındır ki",
      example: "Obviously, the cheaper option saves money.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["clearly", "evidently"],
      pitfall: "Hər şeyə 'obviously' demə — qarşı tərəfi bilmir kimi göstərə bilər.",
    },
    {
      phrase: "clearly",
      level: "B2",
      meaning: "without doubt; in an obvious way",
      azMeaning: "açıqca, şübhəsiz",
      example: "Clearly, more research is needed.",
      register: "formal",
      position: "Sentence start, followed by a comma.",
      synonyms: ["obviously", "evidently"],
    },
    {
      phrase: "indeed",
      level: "C1",
      meaning: "used to emphasise or confirm a statement",
      azMeaning: "həqiqətən, doğrudan da",
      example: "The test was hard. Indeed, only two students passed.",
      register: "formal",
      position: "Sentence start (comma after) or mid-sentence.",
      synonyms: ["in fact", "certainly"],
    },
    {
      phrase: "above all",
      level: "B2",
      meaning: "most importantly",
      azMeaning: "hər şeydən əvvəl, ən əsası",
      example: "Above all, you must stay calm in an emergency.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["most importantly", "most of all"],
    },
    {
      phrase: "in fact",
      level: "B2",
      meaning: "used to emphasise the truth, often something stronger",
      azMeaning: "əslində, hətta",
      example: "It wasn't easy. In fact, it was the hardest exam of my life.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["actually", "indeed"],
    },
    {
      phrase: "certainly",
      level: "B2",
      meaning: "definitely; without doubt",
      azMeaning: "şübhəsiz, mütləq",
      example: "This is certainly the best option we have.",
      register: "neutral",
      position: "Mid-sentence or sentence start.",
    },
    {
      phrase: "definitely",
      level: "B1",
      meaning: "for sure; without any doubt",
      azMeaning: "qətiyyən, mütləq",
      example: "We should definitely try again.",
      register: "informal",
      position: "Before the main verb or sentence start.",
    },
    {
      phrase: "undoubtedly",
      level: "C1",
      meaning: "without any doubt",
      azMeaning: "şübhəsiz ki",
      example: "She is undoubtedly the best player on the team.",
      register: "formal",
      position: "Mid-sentence or sentence start.",
    },
    {
      phrase: "notably",
      level: "C1",
      meaning: "especially; in a way worth noticing",
      azMeaning: "xüsusilə, nəzərəçarpacaq dərəcədə",
      example: "Several countries, notably Norway, lead in this field.",
      register: "formal",
      position: "Mid-sentence or sentence start.",
    },
    {
      phrase: "more importantly",
      level: "B2",
      meaning: "used to add a more important point",
      azMeaning: "daha önəmlisi",
      example: "It's cheaper and, more importantly, safer.",
      register: "neutral",
      position: "Mid-sentence, with commas, or sentence start.",
    },
    {
      phrase: "needless to say",
      level: "C1",
      meaning: "as you would expect; obviously",
      azMeaning: "demək artıqdır ki, təbii ki",
      example: "Needless to say, everyone was exhausted after the trip.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
    },
    {
      phrase: "without doubt",
      level: "B2",
      meaning: "certainly; surely",
      azMeaning: "şübhəsiz",
      example: "This is without doubt the finest restaurant in town.",
      register: "neutral",
      position: "Mid-sentence or sentence start.",
      synonyms: ["without a doubt", "undoubtedly"],
    },
  ],
  practice: [
    {
      type: "gap-fill",
      prompt: "Above ___, never give up. (most importantly, one word)",
      answer: "all",
      explanation: "'Above all' highlights the most important point.",
    },
    {
      type: "multiple-choice",
      prompt: "Which CONFIRMS a statement with strong emphasis?",
      options: ["above all", "indeed", "of course", "clearly"],
      answer: 1,
      explanation: "'Indeed' confirms and strengthens the previous statement.",
    },
    {
      type: "gap-fill",
      prompt: "It wasn't cheap. In ___, it cost a fortune. (one word)",
      answer: "fact",
      explanation: "'In fact' emphasises a stronger truth.",
    },
    {
      type: "multiple-choice",
      prompt: "Which is the most FORMAL?",
      options: ["of course", "clearly", "obviously", "definitely"],
      answer: 1,
      explanation: "'Clearly' fits formal writing well.",
    },
  ],
};
