import type { ConnectorGroup } from "../types";

export const emphasis: ConnectorGroup = {
  id: "emphasis",
  description: "Use these to stress a point and show that it is important or certain.",
  azDescription: "Bir fikri vurğulayıb onun vacib və ya əmin olduğunu göstərmək üçün.",
  connectors: [
    {
      phrase: "of course",
      level: "B1",
      meaning: "used to say something is obvious or expected",
      example: "Of course, you can borrow my car.",
      register: "neutral",
      position: "Sentence start (comma after) or mid-sentence.",
      synonyms: ["naturally", "obviously"],
      azNote: "'Əlbəttə' — aydın/gözlənilən şey.",
    },
    {
      phrase: "obviously",
      level: "B2",
      meaning: "in a way that is easy to see or understand",
      example: "Obviously, the cheaper option saves money.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["clearly", "evidently"],
      pitfall: "Hər şeyə 'obviously' demə — qarşı tərəfi bilmir kimi göstərə bilər.",
      azNote: "'Aydındır ki / açıq-aşkar'.",
    },
    {
      phrase: "clearly",
      level: "B2",
      meaning: "without doubt; in an obvious way",
      example: "Clearly, more research is needed.",
      register: "formal",
      position: "Sentence start, followed by a comma.",
      synonyms: ["obviously", "evidently"],
      azNote: "'Açıqca / şübhəsiz'.",
    },
    {
      phrase: "indeed",
      level: "C1",
      meaning: "used to emphasise or confirm a statement",
      example: "The test was hard. Indeed, only two students passed.",
      register: "formal",
      position: "Sentence start (comma after) or mid-sentence.",
      synonyms: ["in fact", "certainly"],
      azNote: "Təsdiq/güclü vurğu — 'həqiqətən / doğrudan da'.",
    },
    {
      phrase: "above all",
      level: "B2",
      meaning: "most importantly",
      example: "Above all, you must stay calm in an emergency.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["most importantly", "most of all"],
      azNote: "Ən vacib məqamı önə çıxarır — 'hər şeydən əvvəl'.",
    },
    {
      phrase: "in fact",
      level: "B2",
      meaning: "used to emphasise the truth, often something stronger",
      example: "It wasn't easy. In fact, it was the hardest exam of my life.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["actually", "indeed"],
      azNote: "Reallığı vurğular, çox vaxt daha güclü fikir əlavə edir.",
    },
  ],
  practice: [
    {
      type: "gap-fill",
      prompt: "Above ___, never give up. (most importantly, one word)",
      answer: "all",
      explanation: "'Above all' highlights the most important point.",
    },
    {
      type: "multiple-choice",
      prompt: "Which CONFIRMS a statement with strong emphasis?",
      options: ["above all", "indeed", "of course", "clearly"],
      answer: 1,
      explanation: "'Indeed' confirms and strengthens the previous statement.",
    },
    {
      type: "gap-fill",
      prompt: "It wasn't cheap. In ___, it cost a fortune. (one word)",
      answer: "fact",
      explanation: "'In fact' emphasises a stronger truth.",
    },
    {
      type: "multiple-choice",
      prompt: "Which is the most FORMAL?",
      options: ["of course", "clearly", "obviously", "definitely"],
      answer: 1,
      explanation: "'Clearly' fits formal writing well.",
    },
  ],
};
