import type { ConnectorGroup } from "../types";

export const example: ConnectorGroup = {
  id: "example",
  description: "Use these to introduce an example that supports or illustrates your point.",
  azDescription: "Fikrini dəstəkləyən bir nümunə verəndə işlədilir.",
  connectors: [
    {
      phrase: "for example",
      level: "B1",
      meaning: "used to introduce an example",
      example: "Some animals, for example dolphins, are very intelligent.",
      register: "neutral",
      position: "Sentence start (comma after) or mid-sentence between commas.",
      synonyms: ["for instance", "such as"],
      azNote: "Ən geniş işlənən — 'məsələn'. Yazıda 'e.g.' kimi qısaldılır.",
    },
    {
      phrase: "for instance",
      level: "B2",
      meaning: "for example",
      example: "You could exercise more. For instance, you could walk to work.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["for example"],
      azNote: "'for example' ilə demək olar eyni — yan-yana işlədəndə təkrardan qaç.",
    },
    {
      phrase: "such as",
      level: "B1",
      meaning: "like; for example (before nouns)",
      example: "I enjoy team sports such as football and basketball.",
      register: "neutral",
      position: "Directly before a noun or list of nouns.",
      pitfall: "'such as' ardınca isim gəlir, bütöv cümlə YOX. Çox vaxt vergülə ehtiyac olmur.",
      azNote: "Birbaşa isimdən əvvəl — 'kimi'.",
    },
    {
      phrase: "like",
      level: "B1",
      meaning: "for example (informal, before nouns)",
      example: "I like sweet things, like chocolate and ice cream.",
      register: "informal",
      position: "Before a noun.",
      synonyms: ["such as"],
      pitfall: "Rəsmi yazıda 'like' əvəzinə 'such as' işlət.",
      azNote: "Danışıqda 'such as'-in qeyri-rəsmi qarşılığı.",
    },
    {
      phrase: "namely",
      level: "C1",
      meaning: "that is to say; specifically",
      example: "Only one student passed, namely Ahmed.",
      register: "formal",
      position: "Before the specific item(s) you mean.",
      synonyms: ["specifically", "that is"],
      azNote: "Konkret olaraq kimi/nəyi nəzərdə tutduğunu deyəndə — 'yəni'.",
    },
    {
      phrase: "to illustrate",
      level: "C1",
      meaning: "used to introduce an example that explains a point",
      example: "To illustrate, consider the case of online shopping.",
      register: "academic",
      position: "Sentence start, followed by a comma.",
      synonyms: ["as an illustration", "by way of example"],
      azNote: "Akademik — bir fikri nümunə ilə aydınlaşdırmaq.",
    },
    {
      phrase: "in particular",
      level: "B2",
      meaning: "especially; used to highlight one example",
      example: "The museum has great art. In particular, the modern wing is excellent.",
      register: "neutral",
      position: "Sentence start or mid-sentence.",
      synonyms: ["especially", "particularly"],
      azNote: "Bir nümunəni xüsusi vurğulamaq — 'xüsusən'.",
    },
  ],
  practice: [
    {
      type: "multiple-choice",
      prompt: "Which goes directly before a NOUN (not a full clause)?",
      options: ["for example", "such as", "for instance", "to illustrate"],
      answer: 1,
      explanation: "'such as football' — directly before nouns.",
    },
    {
      type: "gap-fill",
      prompt: "Many cities, for ___, London and Paris, are very expensive. (one word)",
      answer: "example",
      accept: ["instance"],
      explanation: "'for example / for instance' introduces examples.",
    },
    {
      type: "multiple-choice",
      prompt: "Which is the most INFORMAL?",
      options: ["such as", "like", "for example", "namely"],
      answer: 1,
      explanation: "'like' (for examples) is informal; use 'such as' in writing.",
    },
    {
      type: "gap-fill",
      prompt: "Only one team qualified, ___ Brazil. (specifically; one word)",
      answer: "namely",
      explanation: "'namely' specifies exactly who/what you mean.",
    },
    {
      type: "multiple-choice",
      prompt: "Choose the correct sentence:",
      options: [
        "I like fruits such as it is sweet.",
        "I like fruits such as mangoes and grapes.",
        "I like fruits such mangoes and grapes.",
        "I like fruits such as are sweet.",
      ],
      answer: 1,
      explanation: "'such as' is followed by nouns, not a clause.",
    },
  ],
};
