import type { ConnectorGroup } from "../types";

export const opinion: ConnectorGroup = {
  id: "opinion",
  description: "Use these to make it clear that you are giving your own personal view.",
  azDescription: "Öz şəxsi fikrini bildirdiyini göstərmək üçün işlədilir.",
  connectors: [
    {
      phrase: "I think",
      level: "B1",
      meaning: "used to give your opinion",
      example: "I think this is the best option.",
      register: "informal",
      position: "Sentence start, before the opinion.",
      synonyms: ["I believe", "I feel"],
      azNote: "Ən sadə fikir bildirmə — 'düşünürəm ki'.",
    },
    {
      phrase: "in my opinion",
      level: "B1",
      meaning: "according to what I believe",
      example: "In my opinion, the film was too long.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in my view", "to my mind"],
      pitfall: "'In my opinion, I think...' təkrardır — birini seç.",
      azNote: "Cümlə başında, sonra vergül — 'məncə / fikrimcə'.",
    },
    {
      phrase: "personally",
      level: "B2",
      meaning: "used to stress that this is just your own view",
      example: "Personally, I prefer tea to coffee.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["for my part"],
      azNote: "Şəxsən öz fikrini vurğulayır — 'şəxsən mən'.",
    },
    {
      phrase: "as far as I'm concerned",
      level: "B2",
      meaning: "in my opinion (often when others may disagree)",
      example: "As far as I'm concerned, the meeting was a waste of time.",
      register: "informal",
      position: "Sentence start, followed by a comma.",
      azNote: "Güclü şəxsi mövqe — 'mənə qalsa'.",
    },
    {
      phrase: "from my point of view",
      level: "B2",
      meaning: "considering things from my position",
      example: "From my point of view, remote work has more benefits.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in my view"],
      azNote: "'Mənim baxış bucağımdan'.",
    },
    {
      phrase: "it seems to me that",
      level: "C1",
      meaning: "used to give an opinion in a softer, more careful way",
      example: "It seems to me that the policy needs rethinking.",
      register: "formal",
      position: "Sentence start, before a clause.",
      synonyms: ["I would argue that", "it appears that"],
      azNote: "Yumşaq, ehtiyatlı fikir — 'mənə elə gəlir ki'.",
    },
  ],
  practice: [
    {
      type: "gap-fill",
      prompt: "In my ___, the second plan is better. (one word)",
      answer: "opinion",
      explanation: "'In my opinion' introduces a personal view.",
    },
    {
      type: "multiple-choice",
      prompt: "Which sentence is WRONG (repetition)?",
      options: [
        "In my opinion, prices are too high.",
        "Personally, I prefer the city.",
        "In my opinion, I think prices are too high.",
        "It seems to me that prices are too high.",
      ],
      answer: 2,
      explanation: "'In my opinion' + 'I think' repeats the same idea — use one.",
    },
    {
      type: "gap-fill",
      prompt: "As far as I'm ___, the rule is unfair. (one word)",
      answer: "concerned",
      explanation: "The phrase is 'as far as I'm concerned'.",
    },
    {
      type: "multiple-choice",
      prompt: "Which is the most CAREFUL / softened opinion?",
      options: ["I think", "as far as I'm concerned", "it seems to me that", "personally"],
      answer: 2,
      explanation: "'It seems to me that' softens the opinion.",
    },
  ],
};
