import type { ConnectorGroup } from "../types";

export const opinion: ConnectorGroup = {
  id: "opinion",
  description: "Use these to make it clear that you are giving your own personal view.",
  azDescription: "Öz şəxsi fikrini bildirdiyini göstərmək üçün işlədilir.",
  connectors: [
    {
      phrase: "I think",
      level: "B1",
      meaning: "used to give your opinion",
      azMeaning: "məncə, düşünürəm ki",
      example: "I think this is the best option.",
      register: "informal",
      position: "Sentence start, before the opinion.",
      synonyms: ["I believe", "I feel"],
    },
    {
      phrase: "in my opinion",
      level: "B1",
      meaning: "according to what I believe",
      azMeaning: "fikrimcə, məncə",
      example: "In my opinion, the film was too long.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in my view", "to my mind"],
      pitfall: "'In my opinion, I think...' təkrardır — birini seç.",
    },
    {
      phrase: "personally",
      level: "B2",
      meaning: "used to stress that this is just your own view",
      azMeaning: "şəxsən mən, mənə görə",
      example: "Personally, I prefer tea to coffee.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["for my part"],
    },
    {
      phrase: "as far as I'm concerned",
      level: "B2",
      meaning: "in my opinion (often when others may disagree)",
      azMeaning: "mənə qalsa, məncə",
      example: "As far as I'm concerned, the meeting was a waste of time.",
      register: "informal",
      position: "Sentence start, followed by a comma.",
      azNote: "Güclü şəxsi mövqe bildirir.",
    },
    {
      phrase: "from my point of view",
      level: "B2",
      meaning: "considering things from my position",
      azMeaning: "mənim baxış bucağımdan",
      example: "From my point of view, remote work has more benefits.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in my view"],
    },
    {
      phrase: "it seems to me that",
      level: "C1",
      meaning: "used to give an opinion in a softer, more careful way",
      azMeaning: "mənə elə gəlir ki",
      example: "It seems to me that the policy needs rethinking.",
      register: "formal",
      position: "Sentence start, before a clause.",
      synonyms: ["I would argue that", "it appears that"],
      azNote: "Yumşaq, ehtiyatlı fikir bildirir.",
    },
    {
      phrase: "in my view",
      level: "B2",
      meaning: "according to what I think",
      azMeaning: "fikrimcə",
      example: "In my view, the rule is unfair.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in my opinion", "to my mind"],
    },
    {
      phrase: "to my mind",
      level: "C1",
      meaning: "in my opinion",
      azMeaning: "mənim fikrimcə",
      example: "To my mind, this is the best solution.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
    },
    {
      phrase: "I believe",
      level: "B1",
      meaning: "used to give an opinion you feel sure about",
      azMeaning: "inanıram ki, məncə",
      example: "I believe everyone deserves a second chance.",
      register: "neutral",
      position: "Sentence start, before the opinion.",
      synonyms: ["I think", "I feel"],
    },
    {
      phrase: "as I see it",
      level: "B2",
      meaning: "from my way of understanding the situation",
      azMeaning: "mənim gördüyüm kimi, məncə",
      example: "As I see it, we have two options.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
    },
    {
      phrase: "if you ask me",
      level: "B2",
      meaning: "used to give your opinion (informal)",
      azMeaning: "mənə sorsan, məncə",
      example: "If you ask me, the price is far too high.",
      register: "informal",
      position: "Sentence start, followed by a comma.",
    },
    {
      phrase: "to be honest",
      level: "B2",
      meaning: "used to give your true, direct opinion",
      azMeaning: "açığı, doğrusu",
      example: "To be honest, I didn't enjoy the film.",
      register: "informal",
      position: "Sentence start, followed by a comma.",
    },
    {
      phrase: "I would argue that",
      level: "C1",
      meaning: "used to give an opinion you can support with reasons",
      azMeaning: "iddia edərdim ki",
      example: "I would argue that quality matters more than price.",
      register: "formal",
      position: "Sentence start, before a clause.",
    },
  ],
  practice: [
    {
      type: "gap-fill",
      prompt: "In my ___, the second plan is better. (one word)",
      answer: "opinion",
      explanation: "'In my opinion' introduces a personal view.",
    },
    {
      type: "multiple-choice",
      prompt: "Which sentence is WRONG (repetition)?",
      options: [
        "In my opinion, prices are too high.",
        "Personally, I prefer the city.",
        "In my opinion, I think prices are too high.",
        "It seems to me that prices are too high.",
      ],
      answer: 2,
      explanation: "'In my opinion' + 'I think' repeats the same idea — use one.",
    },
    {
      type: "gap-fill",
      prompt: "As far as I'm ___, the rule is unfair. (one word)",
      answer: "concerned",
      explanation: "The phrase is 'as far as I'm concerned'.",
    },
    {
      type: "multiple-choice",
      prompt: "Which is the most CAREFUL / softened opinion?",
      options: ["I think", "as far as I'm concerned", "it seems to me that", "personally"],
      answer: 2,
      explanation: "'It seems to me that' softens the opinion.",
    },
  ],
};
