import type { ConnectorGroup } from "../types";

export const purpose: ConnectorGroup = {
  id: "purpose",
  description: "Use these to explain the purpose or goal of an action — to answer 'what for?'.",
  azDescription: "Bir işin məqsədini/niyyətini bildirəndə işlədilir — 'nə üçün?' sualına cavab.",
  connectors: [
    {
      phrase: "in order to",
      level: "B2",
      meaning: "with the purpose of (doing something)",
      azMeaning: "...mək üçün",
      example: "She woke up early in order to catch the train.",
      register: "formal",
      position: "Followed by an infinitive (to + base verb).",
      synonyms: ["so as to", "to"],
      pitfall: "Ardınca məsdər: 'in order to finish'. İnkar: 'in order not to'.",
    },
    {
      phrase: "so as to",
      level: "C1",
      meaning: "in order to",
      azMeaning: "...mək üçün",
      example: "He spoke slowly so as to be understood.",
      register: "formal",
      position: "Followed by an infinitive (to + base verb).",
      pitfall: "İnkar 'so as NOT to' olur — 'so as to not' YANLIŞ.",
    },
    {
      phrase: "so that",
      level: "B2",
      meaning: "with the purpose or result that",
      azMeaning: "...sın deyə, ki",
      example: "I'll write it down so that you don't forget.",
      register: "neutral",
      position: "Followed by a clause (subject + verb), often with can/will/would.",
      azNote: "'so as to'-dan fərqli: ardınca tam cümlə gəlir.",
    },
    {
      phrase: "with the aim of",
      level: "C1",
      meaning: "with the goal of (doing something)",
      azMeaning: "...məqsədiylə",
      example: "They met with the aim of reaching a deal.",
      register: "formal",
      position: "Followed by a noun or -ing form.",
    },
    {
      phrase: "with a view to",
      level: "C1",
      meaning: "with the intention of (doing something later)",
      azMeaning: "...niyyətiylə, ...məqsədiylə",
      example: "He saved money with a view to buying a house.",
      register: "academic",
      position: "Followed by a noun or -ing form.",
      pitfall: "Ardınca -ing gəlir: 'with a view to buying' (with a view to buy YOX).",
    },
    {
      phrase: "in order that",
      level: "C1",
      meaning: "so that (formal)",
      azMeaning: "...sın deyə (rəsmi)",
      example: "The rules were simplified in order that everyone could follow them.",
      register: "academic",
      position: "Followed by a clause.",
      synonyms: ["so that"],
    },
    {
      phrase: "for",
      level: "B2",
      meaning: "for the purpose of (used with a noun or -ing)",
      azMeaning: "...üçün",
      example: "This tool is used for cutting metal.",
      register: "neutral",
      position: "Followed by a noun or -ing form.",
      azNote: "Məqsəd üçün ardınca isim/-ing: 'for cutting'. Feil üçün 'to': 'to cut'.",
    },
  ],
  practice: [
    {
      type: "multiple-choice",
      prompt: "Which is followed by an infinitive (to + verb)?",
      options: ["so that", "in order to", "with the aim of", "for"],
      answer: 1,
      explanation: "'in order to + base verb'; 'so that' takes a clause; 'with the aim of/for' take a noun or -ing.",
    },
    {
      type: "gap-fill",
      prompt: "She left early ___ order to catch the train. (one word)",
      answer: "in",
      explanation: "The phrase is 'in order to'.",
    },
    {
      type: "gap-fill",
      prompt: "I'll repeat it ___ that you don't forget. (one word)",
      answer: "so",
      explanation: "'so that + clause' expresses purpose.",
    },
    {
      type: "multiple-choice",
      prompt: "Which is followed by the -ing form?",
      options: ["in order to", "so as to", "with a view to", "so that"],
      answer: 2,
      explanation: "'with a view to buying' — 'with a view to' takes -ing.",
    },
    {
      type: "multiple-choice",
      prompt: "Choose the correct sentence:",
      options: [
        "He spoke up so as to not be ignored.",
        "He spoke up so as not to be ignored.",
        "He spoke up so not as to be ignored.",
        "He spoke up as so not to be ignored.",
      ],
      answer: 1,
      explanation: "The negative of 'so as to' is 'so as not to'.",
    },
  ],
};
