import type { ConnectorGroup } from "../types";

export const sequence: ConnectorGroup = {
  id: "sequence",
  description: "Use these to put ideas or events in order — first, next, finally.",
  azDescription: "Fikirləri və ya hadisələri ardıcıllıqla düzəndə işlədilir.",
  connectors: [
    {
      phrase: "first / firstly",
      level: "B1",
      meaning: "used to introduce the first point or step",
      example: "First, preheat the oven. Then add the flour.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["to begin with", "first of all"],
      azNote: "Sıralamanın ilk addımı. 'Firstly' yazıda daha rəsmidir.",
    },
    {
      phrase: "then",
      level: "B1",
      meaning: "after that; next",
      example: "We had dinner, then we watched a film.",
      register: "neutral",
      position: "Sentence start or mid-sentence.",
      synonyms: ["after that", "next"],
      azNote: "Bir addımdan o birinə keçid — 'sonra'.",
    },
    {
      phrase: "after that",
      level: "B1",
      meaning: "following that event",
      example: "We visited the museum. After that, we had lunch.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["then", "next", "afterwards"],
      azNote: "'Bundan sonra' — hadisələr arasında.",
    },
    {
      phrase: "next",
      level: "B1",
      meaning: "immediately after",
      example: "Next, we'll look at the results.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["then", "after that"],
      azNote: "'Növbəti olaraq'.",
    },
    {
      phrase: "meanwhile",
      level: "B2",
      meaning: "at the same time; in the period between two events",
      example: "I cooked dinner. Meanwhile, the kids set the table.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in the meantime", "at the same time"],
      azNote: "Eyni vaxtda baş verən başqa hadisə — 'bu arada'.",
    },
    {
      phrase: "subsequently",
      level: "C1",
      meaning: "afterwards; later (formal)",
      example: "The company was fined and subsequently went bankrupt.",
      register: "academic",
      position: "Mid-sentence or sentence start.",
      synonyms: ["afterwards", "later"],
      azNote: "Rəsmi 'sonradan'.",
    },
    {
      phrase: "finally",
      level: "B1",
      meaning: "used to introduce the last point or step",
      example: "Finally, add salt and serve the dish.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["lastly", "in the end"],
      pitfall: "'Finally' (sıralama) ≠ 'at last' (uzun gözlədikdən sonra rahatlıq).",
      azNote: "Sonuncu addım — 'nəhayət / son olaraq'.",
    },
  ],
  practice: [
    {
      type: "gap-fill",
      prompt: "___, preheat the oven. Then mix the eggs and sugar. (the first step, one word)",
      answer: "first",
      accept: ["firstly"],
      explanation: "'First/Firstly' introduces the first step.",
    },
    {
      type: "multiple-choice",
      prompt: "Which means 'at the same time'?",
      options: ["finally", "meanwhile", "first", "next"],
      answer: 1,
      explanation: "'Meanwhile' = during the same period.",
    },
    {
      type: "gap-fill",
      prompt: "We saw the castle. After ___, we walked to the river. (one word)",
      answer: "that",
      explanation: "The phrase is 'after that'.",
    },
    {
      type: "multiple-choice",
      prompt: "Which introduces the LAST point in a list?",
      options: ["first", "then", "finally", "meanwhile"],
      answer: 2,
      explanation: "'Finally' marks the final step.",
    },
    {
      type: "multiple-choice",
      prompt: "Choose the most FORMAL word for 'afterwards':",
      options: ["then", "subsequently", "after that", "next"],
      answer: 1,
      explanation: "'Subsequently' is the formal/academic choice.",
    },
  ],
};
