import type { ConnectorGroup } from "../types";

export const sequence: ConnectorGroup = {
  id: "sequence",
  description: "Use these to put ideas or events in order — first, next, finally.",
  azDescription: "Fikirləri və ya hadisələri ardıcıllıqla düzəndə işlədilir.",
  connectors: [
    {
      phrase: "first / firstly",
      level: "B1",
      meaning: "used to introduce the first point or step",
      azMeaning: "əvvəlcə, birincisi",
      example: "First, preheat the oven. Then add the flour.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["to begin with", "first of all"],
      azNote: "'Firstly' yazıda daha rəsmidir.",
    },
    {
      phrase: "then",
      level: "B1",
      meaning: "after that; next",
      azMeaning: "sonra",
      example: "We had dinner, then we watched a film.",
      register: "neutral",
      position: "Sentence start or mid-sentence.",
      synonyms: ["after that", "next"],
    },
    {
      phrase: "after that",
      level: "B1",
      meaning: "following that event",
      azMeaning: "bundan sonra",
      example: "We visited the museum. After that, we had lunch.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["then", "next", "afterwards"],
    },
    {
      phrase: "next",
      level: "B1",
      meaning: "immediately after",
      azMeaning: "növbəti olaraq, sonra",
      example: "Next, we'll look at the results.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["then", "after that"],
    },
    {
      phrase: "meanwhile",
      level: "B2",
      meaning: "at the same time; in the period between two events",
      azMeaning: "bu arada, eyni vaxtda",
      example: "I cooked dinner. Meanwhile, the kids set the table.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["in the meantime", "at the same time"],
    },
    {
      phrase: "subsequently",
      level: "C1",
      meaning: "afterwards; later (formal)",
      azMeaning: "sonradan, ardınca",
      example: "The company was fined and subsequently went bankrupt.",
      register: "academic",
      position: "Mid-sentence or sentence start.",
      synonyms: ["afterwards", "later"],
      azNote: "Rəsmi üslub.",
    },
    {
      phrase: "finally",
      level: "B1",
      meaning: "used to introduce the last point or step",
      azMeaning: "nəhayət, son olaraq",
      example: "Finally, add salt and serve the dish.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["lastly", "in the end"],
      pitfall: "'Finally' (sıralama) ≠ 'at last' (uzun gözlədikdən sonra rahatlıq).",
    },
    {
      phrase: "first of all",
      level: "B1",
      meaning: "before anything else (the first point)",
      azMeaning: "ilk öncə, hər şeydən əvvəl",
      example: "First of all, let me thank you all for coming.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["to begin with", "firstly"],
    },
    {
      phrase: "to begin with",
      level: "B2",
      meaning: "as a first point",
      azMeaning: "əvvəla, başlamaq üçün",
      example: "To begin with, the hotel was far from the centre.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
      synonyms: ["to start with", "first of all"],
    },
    {
      phrase: "secondly",
      level: "B1",
      meaning: "used to introduce the second point",
      azMeaning: "ikincisi",
      example: "Secondly, the price is far too high.",
      register: "neutral",
      position: "Sentence start, followed by a comma.",
    },
    {
      phrase: "afterwards",
      level: "B2",
      meaning: "after that; later",
      azMeaning: "sonra, daha sonra",
      example: "We had dinner and went for a walk afterwards.",
      register: "neutral",
      position: "End of sentence or sentence start.",
    },
    {
      phrase: "eventually",
      level: "B2",
      meaning: "in the end, after a long time",
      azMeaning: "nəhayət, axırda",
      example: "After many tries, he eventually passed the exam.",
      register: "neutral",
      position: "Mid-sentence or sentence start.",
      pitfall: "'eventually' = nəhayət/zamanla; 'finally' = son addım.",
    },
    {
      phrase: "in the end",
      level: "B2",
      meaning: "finally, after everything",
      azMeaning: "sonda, axırda",
      example: "We argued a lot, but in the end we agreed.",
      register: "neutral",
      position: "Sentence start or end.",
      pitfall: "'in the end' (sonda nəticə) ≠ 'at the end' (bir şeyin sonunda).",
    },
    {
      phrase: "prior to",
      level: "C1",
      meaning: "before",
      azMeaning: "...-dən əvvəl",
      example: "Prior to the meeting, please read the report.",
      register: "formal",
      position: "Followed by a noun or -ing form.",
      synonyms: ["before"],
    },
    {
      phrase: "as soon as",
      level: "B2",
      meaning: "immediately when",
      azMeaning: "...-an kimi, dərhal",
      example: "Call me as soon as you arrive.",
      register: "neutral",
      position: "Starts a time clause.",
      pitfall: "Gələcək üçün present işlət: 'as soon as you arrive' (will yox).",
    },
  ],
  practice: [
    {
      type: "gap-fill",
      prompt: "___, preheat the oven. Then mix the eggs and sugar. (the first step, one word)",
      answer: "first",
      accept: ["firstly"],
      explanation: "'First/Firstly' introduces the first step.",
    },
    {
      type: "multiple-choice",
      prompt: "Which means 'at the same time'?",
      options: ["finally", "meanwhile", "first", "next"],
      answer: 1,
      explanation: "'Meanwhile' = during the same period.",
    },
    {
      type: "gap-fill",
      prompt: "We saw the castle. After ___, we walked to the river. (one word)",
      answer: "that",
      explanation: "The phrase is 'after that'.",
    },
    {
      type: "multiple-choice",
      prompt: "Which introduces the LAST point in a list?",
      options: ["first", "then", "finally", "meanwhile"],
      answer: 2,
      explanation: "'Finally' marks the final step.",
    },
    {
      type: "multiple-choice",
      prompt: "Choose the most FORMAL word for 'afterwards':",
      options: ["then", "subsequently", "after that", "next"],
      answer: 1,
      explanation: "'Subsequently' is the formal/academic choice.",
    },
  ],
};
