import type { Topic } from "../types";
export const b2SocialMedia: Topic = {
  id: "b2-social-media", level: "B2", title: "Social Media and Society", theme: "Media",
  summary: "Explore how social media shapes modern life, and learn to describe processes and effects with the passive voice.",
  leadIn: [
    "How many hours a day are spent on social media in your country?",
    "Should children be allowed to use social networks?",
    "Has social media made society more connected or more divided?",
  ],
  vocabulary: [
    { word: "influence", definition: "the power to affect how people think, feel, or behave", example: "The opinions of popular creators are influenced by the brands that pay them.", collocations: ["have an influence", "under the influence"], azNote: "təsir, nüfuz; bir kəsin düşüncəsinə, hisslərinə və ya davranışına təsir etmək gücü" },
    { word: "algorithm", definition: "a set of rules a computer follows to decide what content you see", example: "Your feed is arranged by an algorithm that studies every click.", collocations: ["recommendation algorithm", "the algorithm decides"], azNote: "alqoritm, kompüterin hansı məzmunu göstərəcəyini həll etmək üçün izlədiyi qaydalar toplusu" },
    { word: "addictive", definition: "very hard to stop doing once you have started", example: "Endless scrolling is designed to be addictive.", collocations: ["highly addictive", "addictive behaviour"], azNote: "asılılıq yaradan, başlandıqdan sonra dayandırması çox çətin olan" },
    { word: "misinformation", definition: "false or misleading information that is spread, often without bad intent", example: "During the election, a wave of misinformation was shared by millions of users.", collocations: ["spread misinformation", "tackle misinformation"], azNote: "yanlış məlumat, çox vaxt qəsdsiz yayılan səhv və ya çaşdırıcı məlumat" },
    { word: "privacy", definition: "the state of keeping personal information away from others", example: "Many people feel their privacy is no longer protected online.", collocations: ["invade someone's privacy", "privacy settings"], azNote: "məxfilik, şəxsi məlumatın başqalarından qorunması vəziyyəti" },
    { word: "scroll", definition: "to move text or images up or down on a screen", example: "I tend to scroll through my phone for hours without noticing.", collocations: ["scroll through", "endless scroll"], azNote: "ekranda mətni və ya şəkilləri yuxarı-aşağı sürüşdürmək, vərəqləmək" },
  ],
  grammar: {
    point: "The passive voice (is/are + past participle; was/were; has been)",
    explanation: "The passive voice is formed with the verb 'be' plus a past participle, for example 'is shared' or 'was created'. It is used when the action matters more than the person who does it, or when the doer is unknown or obvious. The agent can be added with 'by', as in 'The post was deleted by a moderator'.",
    azNote: "Passiv konstruksiya 'be' feili ilə üçüncü formanın birləşməsindən yaranır, məsələn 'is shared', 'was created'. Hərəkəti edən şəxs naməlum və ya əhəmiyyətsiz olanda işlədilir, edəni göstərmək üçün isə 'by' əlavə olunur.",
    examples: [
      { en: "Billions of messages are sent every single day.", note: "present simple passive: are + sent" },
      { en: "The platform was launched in 2004.", note: "past simple passive: was + launched" },
      { en: "Your data has been collected and sold to advertisers.", note: "present perfect passive: has been + collected" },
      { en: "Harmful posts are removed by automated systems.", note: "agent introduced with 'by'" },
    ],
  },
  reading: {
    title: "Living Through the Screen",
    text: `Social media has changed the way societies communicate, and its effects are now studied carefully by researchers around the world. Every time an app is opened, a personalised feed is generated by an algorithm that has learned exactly what keeps us watching. Content is not shown in a neutral order; instead, the posts most likely to grab our attention are pushed to the top, and we are encouraged to scroll for far longer than we intended.

This design is no accident. The endless feed was created to be addictive, because companies earn money when our time and attention are captured. As a result, users are kept on the platform through likes, notifications and surprising videos. The influence of these tools is enormous: opinions are shaped, products are sold, and even elections are affected by what is shared online.

There is, however, a darker side. Because anything can be posted in seconds, misinformation is spread quickly and is often believed before it can be checked. False stories are forwarded by ordinary people who simply trust their friends. At the same time, personal data is constantly gathered, and many users feel that their privacy has been lost completely. Photos, locations and messages are stored on servers that they will never see.

So what can be done? Stronger laws are being introduced in several countries, and platforms are now required to remove harmful content more quickly. Yet real change also depends on us. If healthier habits are built and screen time is limited, social media can still be enjoyed without being controlled by it. The technology itself is not the enemy; the question is whether it is used wisely or allowed to run our lives.`,
    questions: [
      { type: "multiple-choice", prompt: "Why are posts that grab attention pushed to the top of the feed?", options: ["Because users request them", "Because the algorithm is designed to keep people watching", "Because they are checked for accuracy", "Because governments require it"], answer: 1, explanation: "The text says the feed is generated by an algorithm that has learned what keeps us watching." },
      { type: "multiple-choice", prompt: "According to the text, why does misinformation spread so easily?", options: ["Because it is always true", "Because anything can be posted in seconds and is often believed before being checked", "Because algorithms delete real news", "Because laws encourage it"], answer: 1, explanation: "The passage explains that anything can be posted in seconds, so false stories are believed before they can be checked." },
      { type: "multiple-choice", prompt: "What does the writer suggest at the end of the text?", options: ["Social media should be banned completely", "Technology is the real enemy", "With healthier habits, social media can still be enjoyed", "Nothing can be done about the problem"], answer: 2, explanation: "The final paragraph says that if healthier habits are built, social media can still be enjoyed without controlling us." },
    ],
  },
  speaking: [
    "Describe how a typical day of yours is affected by social media.",
    "Some say privacy has already been lost online. Do you agree, and why?",
    "What should be done by governments to reduce the spread of misinformation?",
  ],
  writing: { task: "Write an opinion essay about whether social media has a positive or negative influence on society. Use the passive voice at least four times and include at least three topic words.", minWords: 150 },
  quiz: [
    { type: "gap-fill", prompt: "Billions of messages ___ (send) every day on social platforms.", answer: "are sent", accept: ["are sent"], explanation: "Present simple passive: are + past participle 'sent'." },
    { type: "gap-fill", prompt: "The app ___ (launch) in 2004 and quickly became popular.", answer: "was launched", accept: ["was launched"], explanation: "Past simple passive: was + past participle 'launched'." },
    { type: "multiple-choice", prompt: "Choose the correct present perfect passive form: 'My personal data ___ collected without my consent.'", options: ["has been", "have being", "is been", "was being"], answer: 0, explanation: "Present perfect passive uses 'has/have been' + past participle; with singular 'data' here we use 'has been collected'." },
    { type: "multiple-choice", prompt: "Which sentence is a correct passive sentence?", options: ["The post deleted by a moderator.", "The post was deleted by a moderator.", "The post is delete by a moderator.", "The post has delete by a moderator."], answer: 1, explanation: "The passive needs 'be' + past participle: 'was deleted'." },
    { type: "multiple-choice", prompt: "Which word means 'false or misleading information that is spread'?", options: ["algorithm", "privacy", "misinformation", "influence"], answer: 2, explanation: "'Misinformation' is false or misleading information, often spread without bad intent." },
  ],
};
