import type { Topic } from "../types";
export const c1Consciousness: Topic = {
  id: "c1-consciousness", level: "C1", title: "The Nature of Consciousness", theme: "Science",
  summary: "Explore competing scientific accounts of consciousness, and learn to hedge claims and link ideas with academic language such as 'it could be argued that', 'tends to', 'appears to', 'insofar as' and 'whereas'.",
  leadIn: ["What do we actually mean when we say a being is conscious?", "Could a sufficiently advanced machine ever have genuine experiences?", "How far can science explain the feeling of being you?"],
  vocabulary: [
    { word: "subjective", definition: "based on or existing within an individual's private experience rather than external, measurable facts", example: "The subjective quality of pain cannot be fully captured by a brain scan.", collocations: ["subjective experience", "deeply subjective"], azNote: "subyektiv, yəni şəxsi təcrübəyə əsaslanan, kənardan ölçülə bilməyən." },
    { word: "emergent", definition: "arising from the complex interaction of simpler parts, while not being reducible to any one of them", example: "Many researchers treat the mind as an emergent property of billions of interacting neurons.", collocations: ["emergent property", "emergent behaviour"], azNote: "emergent, yəni sadə hissələrin qarşılıqlı təsirindən doğan, lakin tək bir hissəyə endirilə bilməyən." },
    { word: "introspection", definition: "the act of examining one's own thoughts, feelings and inner states", example: "Through careful introspection we notice the constant flow of our own awareness.", collocations: ["careful introspection", "rely on introspection"], azNote: "introspeksiya, yəni insanın öz fikir, hiss və daxili vəziyyətlərini müşahidə etməsi." },
    { word: "elusive", definition: "difficult to find, define, capture or fully understand", example: "A precise definition of awareness remains stubbornly elusive.", collocations: ["remain elusive", "an elusive concept"], azNote: "əlçatmaz, yəni tutmaq, müəyyən etmək və ya tam anlamaq çətin olan." },
    { word: "correlate", definition: "a thing or measurable factor that is closely connected with, and varies alongside, another", example: "Scientists search for the neural correlate of a particular conscious thought.", collocations: ["neural correlate", "correlate with activity"], azNote: "korrelyat, yəni başqa bir şeylə sıx bağlı olan və onunla birgə dəyişən ölçülə bilən amil." },
    { word: "phenomenon", definition: "an observable fact or event, especially one whose cause or nature is being studied", example: "Consciousness is perhaps the most puzzling phenomenon known to science.", collocations: ["a strange phenomenon", "study the phenomenon"], azNote: "fenomen, yəni müşahidə oluna bilən, səbəbi və ya təbiəti öyrənilən hadisə." },
  ],
  grammar: {
    point: "Hedging and academic linking (it could be argued that, tends to, appears to, insofar as, whereas)",
    explanation: "In academic English we rarely state claims as absolute facts; instead we hedge them to signal caution and acknowledge uncertainty. Phrases such as 'it could be argued that', 'tends to' and 'appears to' soften assertions, whereas linkers like 'insofar as' and 'whereas' connect and qualify ideas precisely. This cautious, connected style makes an argument sound balanced and scholarly.",
    azNote: "Akademik İngiliscədə fikirlər çox vaxt mütləq həqiqət kimi deyil, ehtiyatla, yəni 'hedging' ilə ifadə olunur. 'It could be argued that', 'tends to' və 'appears to' iddianı yumşaldır, 'insofar as' və 'whereas' isə fikirləri bir-birinə bağlayıb dəqiqləşdirir. Bu üslub mübahisəni balanslı və elmi göstərir.",
    examples: [
      { en: "It could be argued that consciousness is the hardest problem in all of science.", note: "hedged claim, not stated as certain fact" },
      { en: "Brain activity tends to increase when a person reports a vivid experience.", note: "'tends to' shows a general tendency, not an absolute rule" },
      { en: "The mind appears to depend on the brain, yet the exact mechanism remains unclear.", note: "'appears to' signals that the evidence is suggestive rather than conclusive" },
      { en: "Machines may process information insofar as they manipulate symbols, whereas humans seem to feel what they think.", note: "'insofar as' qualifies the claim, 'whereas' draws a contrast" },
    ],
  },
  reading: { title: "The Hard Problem of Awareness",
    text: `Consciousness is arguably the most elusive phenomenon that science has ever attempted to explain. We can measure heartbeats and map galaxies, yet the simple fact that there is something it is like to be you appears to resist every conventional method of investigation. It could be argued that this difficulty is not merely technical but conceptual, insofar as the tools of objective measurement seem poorly suited to a deeply subjective reality.

Most contemporary neuroscientists treat awareness as an emergent property of the brain. On this view, conscious experience tends to arise when vast networks of neurons interact in particular ways, much as the wetness of water emerges from molecules that are not themselves wet. Researchers therefore hunt for the neural correlate of a given experience: the specific pattern of activity that reliably accompanies, say, the perception of the colour red. Such correlates tell us when consciousness is present, whereas they do not, on their own, explain why that activity should feel like anything at all.

The philosopher David Chalmers famously called this the "hard problem". Easy problems, insofar as they concern behaviour and information processing, appear tractable; the hard problem of subjective feeling seems to lie on a different level entirely. Critics of purely physical accounts argue that no amount of objective data can capture the inner texture of experience, which we can reach only through introspection.

Whether machines could ever be conscious remains contested. A system might behave intelligently insofar as it processes information efficiently, whereas it could be argued that genuine feeling demands something more. For now, the question tends to outrun our evidence, and honest researchers admit that the nature of awareness, however carefully we observe it through introspection or instruments, appears destined to remain elusive for some time yet.`,
    questions: [
      { type: "multiple-choice", prompt: "According to the text, why is consciousness described as conceptually, not just technically, difficult?", options: ["Because scientists lack powerful enough brain scanners", "Because objective measurement seems poorly suited to a subjective reality", "Because neurons are too small to observe", "Because galaxies are easier to study"], answer: 1, explanation: "The first paragraph states the difficulty is conceptual insofar as objective measurement seems poorly suited to a deeply subjective reality." },
      { type: "multiple-choice", prompt: "What does a 'neural correlate' tell researchers, according to the passage?", options: ["Why brain activity feels like something", "How to build a conscious machine", "When a given conscious experience is present", "Why water is wet"], answer: 2, explanation: "The text says correlates tell us when consciousness is present, but do not explain why the activity feels like anything." },
      { type: "multiple-choice", prompt: "What is the passage's overall stance on whether machines can be conscious?", options: ["It firmly states machines are already conscious", "It treats the issue as settled and impossible", "It presents it as contested and unresolved", "It claims the question is meaningless"], answer: 2, explanation: "The final paragraph hedges, saying the issue remains contested and the question tends to outrun our evidence." },
    ],
  },
  speaking: ["Outline one scientific and one philosophical view of consciousness, hedging your claims with phrases like 'it could be argued that' and 'appears to'.", "Compare human awareness with artificial intelligence, using 'whereas' and 'insofar as' to draw careful distinctions.", "To what extent can introspection be trusted as evidence about the mind? Justify your position cautiously."],
  writing: { task: "Write an academic paragraph arguing whether consciousness can ever be fully explained by science. Hedge your claims using 'it could be argued that', 'tends to', 'appears to', 'insofar as' and 'whereas', and include at least three topic vocabulary words.", minWords: 140 },
  quiz: [
    { type: "gap-fill", prompt: "Brain activity ___ to increase when people report vivid experiences, though there are exceptions.", answer: "tends", accept: ["tends to"], explanation: "'tends to' is a hedge expressing a general tendency rather than an absolute rule." },
    { type: "gap-fill", prompt: "It could be ___ that consciousness is the hardest problem in science.", answer: "argued", explanation: "The fixed hedging phrase is 'it could be argued that', which softens a strong claim." },
    { type: "multiple-choice", prompt: "Which word best completes an academic contrast: 'Machines process symbols, ___ humans seem to feel what they think.'?", options: ["because", "whereas", "so", "unless"], answer: 1, explanation: "'whereas' introduces a contrast between two clauses, which is exactly what the sentence needs." },
    { type: "multiple-choice", prompt: "Which phrase most cautiously reports uncertain evidence?", options: ["The mind definitely depends on the brain.", "The mind appears to depend on the brain.", "The mind must depend on the brain.", "The mind obviously depends on the brain."], answer: 1, explanation: "'appears to' hedges the claim, signalling that the evidence is suggestive rather than conclusive." },
    { type: "multiple-choice", prompt: "Which word means 'difficult to capture, define or fully understand'?", options: ["emergent", "subjective", "elusive", "introspection"], answer: 2, explanation: "'elusive' describes something hard to grasp or pin down, like a precise definition of awareness." },
  ],
};
