// AUTO-GENERATED by scripts/generate-manifest.ts — ƏLLƏ DƏYİŞMƏ.
// Yenidən yarat: npm run manifest
import type { TopicMeta } from "./types";

export const topicMeta: TopicMeta[] = [
  {
    "id": "b1-travel",
    "level": "B1",
    "title": "Travel & Tourism",
    "theme": "Travel",
    "summary": "Talk about trips and holidays, and learn to describe past travel experiences using the Present Perfect vs Past Simple.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b1-chocolate",
    "level": "B1",
    "title": "The History of Chocolate",
    "theme": "Food",
    "summary": "Discover where chocolate really comes from, and learn to talk about past habits and situations with 'used to'.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b1-dreams",
    "level": "B1",
    "title": "Why Do We Dream?",
    "theme": "Science",
    "summary": "Explore the mystery of dreams, and learn to talk about things that are possible but not certain with 'may', 'might' and 'could'.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b1-animals",
    "level": "B1",
    "title": "The World's Strangest Animals",
    "theme": "Animals",
    "summary": "Meet some of the strangest creatures on Earth, and learn to compare things with comparatives and superlatives.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b1-festivals",
    "level": "B1",
    "title": "Festivals Around the World",
    "theme": "Culture",
    "summary": "Travel the world through its most colourful festivals, and learn the difference between the Present Simple and the Present Continuous.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b1-solar-system",
    "level": "B1",
    "title": "The Solar System",
    "theme": "Space",
    "summary": "Take a journey through our solar system, and learn to talk about the future with 'will' and 'going to'.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b1-volcanoes",
    "level": "B1",
    "title": "Volcanoes & Earthquakes",
    "theme": "Nature",
    "summary": "Learn how our powerful planet shakes and erupts, and practise the first conditional to talk about real future possibilities.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b1-inventions",
    "level": "B1",
    "title": "Inventions That Changed the World",
    "theme": "History",
    "summary": "Learn about the inventions that shaped modern life, and practise the passive voice to say what was made, when and by whom.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b1-sleep",
    "level": "B1",
    "title": "A Good Night's Sleep",
    "theme": "Health",
    "summary": "Find out what really happens when you sleep, and learn to give advice and talk about rules with 'should', 'must' and 'have to'.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b1-money",
    "level": "B1",
    "title": "The Story of Money",
    "theme": "Money",
    "summary": "Follow the history of money from shells to smartphones, and learn to use quantifiers like some, any, much, many and a lot of.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b1-languages",
    "level": "B1",
    "title": "Languages of the World",
    "theme": "Language",
    "summary": "Discover the amazing variety of human languages, and learn to join ideas with relative clauses (who, which, that, where).",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b2-work",
    "level": "B2",
    "title": "Work & Career",
    "theme": "Work",
    "summary": "Discuss jobs, ambitions and the modern workplace, and master the Passive Voice to describe processes and responsibilities.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b2-habits",
    "level": "B2",
    "title": "The Psychology of Habits",
    "theme": "Psychology",
    "summary": "Understand why habits are so hard to break, and master the difference between the Present Perfect Continuous and the Present Perfect Simple.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b2-internet",
    "level": "B2",
    "title": "The History of the Internet",
    "theme": "Technology",
    "summary": "Trace how a military project became the modern internet, and use the Past Perfect to make the order of past events clear.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b2-happiness",
    "level": "B2",
    "title": "The Science of Happiness",
    "theme": "Health",
    "summary": "Explore what really makes people happy, and use the second conditional to talk about imaginary situations and their results.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b2-ai",
    "level": "B2",
    "title": "Living with Artificial Intelligence",
    "theme": "Technology",
    "summary": "Consider how AI is changing our world, and learn to talk about the future with the Future Continuous and the Future Perfect.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b2-advertising",
    "level": "B2",
    "title": "The Art of Advertising",
    "theme": "Business",
    "summary": "Learn the tricks that advertisers use to influence us, and practise reported speech to tell others what people said.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b2-body-language",
    "level": "B2",
    "title": "The Secrets of Body Language",
    "theme": "Communication",
    "summary": "Discover how we 'speak' without words, and use modals of deduction (must, can't, might) to guess what people are feeling.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b2-music",
    "level": "B2",
    "title": "The Power of Music",
    "theme": "Culture",
    "summary": "Find out why music affects us so deeply, and master verb patterns with gerunds (-ing) and infinitives (to + verb).",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b2-fake-news",
    "level": "B2",
    "title": "Fake News & Critical Thinking",
    "theme": "Media",
    "summary": "Learn how false information spreads and how to spot it, and use passive reporting structures such as 'It is said that…'.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b2-cities",
    "level": "B2",
    "title": "The Cities of the Future",
    "theme": "Society",
    "summary": "Imagine how we will live as cities grow, and learn to add extra information with non-defining relative clauses.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "b2-ancient-wonders",
    "level": "B2",
    "title": "Wonders of the Ancient World",
    "theme": "History",
    "summary": "Marvel at what ancient people built, and use the third conditional to imagine how the past could have been different.",
    "vocabCount": 6,
    "quizCount": 5
  },
  {
    "id": "c1-environment",
    "level": "C1",
    "title": "Environment & Climate Change",
    "theme": "Environment",
    "summary": "Engage with abstract arguments about sustainability and climate policy, and use advanced conditional structures (mixed and inverted conditionals) to discuss hypothetical consequences.",
    "vocabCount": 6,
    "quizCount": 5
  }
];
