// Yüngül topic manifestini yaradır — siyahı/filtr üçün lazım olan minimal
// metadata (tam Topic məzmunu yox). Beləcə app açılışda bütün dərslərin
// oxu mətnini/quizini yox, yalnız bu kiçik siyahını yükləyir.
//
// İşlət: npm run manifest   (build avtomatik çağırır)
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { topics } from "../src/content/index";
import type { TopicMeta } from "../src/content/types";

// Qeyd: array sırası saxlanılır — bu, HomePage-dəki göstərmə sırasıdır.
const metas: TopicMeta[] = topics.map((t) => ({
  id: t.id,
  level: t.level,
  title: t.title,
  theme: t.theme,
  summary: t.summary,
  vocabCount: t.vocabulary.length,
  quizCount: t.quiz.length,
}));

const body = `// AUTO-GENERATED by scripts/generate-manifest.ts — ƏLLƏ DƏYİŞMƏ.
// Yenidən yarat: npm run manifest
import type { TopicMeta } from "./types";

export const topicMeta: TopicMeta[] = ${JSON.stringify(metas, null, 2)};
`;

const out = join(process.cwd(), "src", "content", "manifest.generated.ts");
writeFileSync(out, body);
console.log(`✅ ${metas.length} topic → src/content/manifest.generated.ts`);
